### ISSUE TITLE
error with CAPS outputs.

### ISSUE THREAD

**Issue by WY-SHI** [aramis-lab/clinica#103]
We encountered an error about CAPS outputs while running `clinica run t1-volume-tissue-segmentation`:
```
Pipeline finished with errors.
CAPS outputs were not found for some image(s):
Implementation on which image(s) failed will appear soon.
Documentation can be found here: http://www.clinica.run/doc/
If you need support, do not hesitate to ask: https://groups.google.com/forum/#!forum/clinica-user
Alternatively, you can also open an issue on GitHub: https://github.com/aramis-lab/clinica/issues
```
And it would report the same error even we had already made the output file formed with BIDS structure.

**Comment by alexandreroutier** [comment]
Hi,

Thanks for your interest in Clinica!

Could you give us the following information :
- What is your operating system and Matlab version?
- What is the content of your `startup.m` file?
- Could you type the two following commands after activation of the Clinica environment:
```
python -c "import nipype.interfaces.spm as spm; print(spm.Info.getinfo())"
echo $SPM_HOME
```
- What is the command you typed?

Normally, you should have crash files of the form : `crash-<date>-<time>-<user>-<involved_node>-<very_long_hash>.pklz`

Could you copy/paste the result of `nipypecli crash <you pklz crash file>` for some crash files?

Best,
Alexandre

**Comment by WY-SHI** [comment]
Thanks for your reply.

I checked the crash file and solved this problem. Within the BIDS structure implemented by clinica, the file name cannot contain any underscores.

Thanks again for your helpful reply.

**Comment by alexandreroutier** [comment]
Thanks for the feedback.

For curiosity, could you tell us what was inside the crash files? Because we aim to have a message error before the execution of any pipeline which was not the case with you.

Best,
Alex

**Comment by asd567** [comment]
@WY-SHI  Hi, I am sorry to disturb you.

But I have the same error. And I also want to know what's inside. 

Thanks
