### ISSUE TITLE
Add BIDS Conversion for Blood Recording Data into ADNI-to-BIDS 

### ISSUE THREAD

**Issue by Ianyliu** [aramis-lab/clinica#1053]
According to the [BIDS specification for PET](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/positron-emission-tomography.html#blood-recording-data), blood recording data is to be added. Currently when I perform ADNI-to-BIDS for PET imaging, there are no TSV or JSON files in the output folders.

Since (I believe) Clinica BIDS conversion uses PyBIDS, I'm wondering if the portion of the code that uses PyBIDS could be updated, because it seems like they do have blood recording file formatting included in their [code](https://github.com/bids-standard/pybids/blob/9d14b4058cd5f89b3eb4361cf589c4249edaf65b/bids/layout/config/bids.json#L160).

**Comment by nburgos** [comment]
Hi @Ianyliu 
If collected, blood measurements should indeed be stored. To the best of our knowledge, such data are not collected as part of the ADNI study, which appears consistent with the fact that static acquisitions are performed. This explains why there are no TSV nor JSON files in the output folders.
