### ISSUE TITLE
Refactor packaging and installation process

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinica#106]
How to handle requirements properly?

Some clues: 
 - https://packaging.python.org/discussions/install-requires-vs-requirements/
 - https://caremad.io/posts/2013/07/setup-vs-requirement/

Need to refactor the `setup.py` file to include requirements for pip packaging. 

This issue is related to issue #102.

**Comment by alexandreroutier** [comment]
Solved issue with the release of Clinica `v0.3.6`.
