### ISSUE TITLE
aibl_utils.py MRI metadata filenames

### ISSUE THREAD

**Issue by noxtoby** [aramis-lab/clinica#108]
To get the AIBL to BIDS converter working, I had to update lines 468 and 469 of `aibl_utils.py` to the latest filenames (as of July 2020).

Old:
```
    mri_meta = pandas.read_csv(os.path.join(path_to_csv, "aibl_mrimeta_28-Apr-2015.csv"))
    mri_3meta = pandas.read_csv(os.path.join(path_to_csv, "aibl_mri3meta_28-Apr-2015.csv"))

```

New:
```
    mri_meta = pandas.read_csv(os.path.join(path_to_csv, "aibl_mrimeta_01-Jun-2018.csv"))
    mri_3meta = pandas.read_csv(os.path.join(path_to_csv, "aibl_mri3meta_01-Jun-2018.csv"))

```

Might be worth removing the magic filenames and replacing with generic ones that don't depend on the timestamp.

**Comment by alexandreroutier** [comment]
Hello Neil,

Thank you for your feedback regarding `aibl-2-bids` converter :)

Last download of AIBL was few years ago and we were not sure regarding evolution of filenames. Based on your recent download, I think we can safely apply regexp as suggested by you.

Thanks again!

Best,
Alex
