### ISSUE TITLE
Error reading .pt file

### ISSUE THREAD

**Issue by Overnickel** [aramis-lab/clinica#117]
Hi there,

After the "clinica run deeplearning-prepare-data" pipeline, I got the *.pt file.
However, I got such error
```
UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```
when tried to load the *.pt file using torch.load(pt_path)

**Comment by 14thibea** [comment]
Hi!

This error may occur if you saved the tensor files with a more recent version of PyTorch that the one used to load them.
Can you try to load the tensor with the same PyTorch version than the one used by clinica ?
Also be aware that IPython or Jupyter may not use the Python of your environment even if you launch them from this environment.
