### ISSUE TITLE
Change the frequency of execution of the non-regression tests.

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinica#124]
Duration of the running of non-regression tests is becoming larger than 12h. 
Most problems comes from the `t1-freesurfer*` pipelines.
One option is to propose daily and/or weekly runs....

This problem was mentioned in PR #120.

**Comment by ghisvail** [comment]
CI runtimes have improved lately thanks to your continuous efforts.

Should we close this now @mdiazmel ?

**Comment by mdiazmel** [comment]
> Should we close this now @mdiazmel ?

Yes!
