### ISSUE TITLE
Diagnosis conversion for sessions of ADNI3

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinica#126]
Hello,

It seems that there is an issue in the conversion of the diagnoses of ADNI3 sessions as the columns `adni_diagnosis_change` and `diagnosis` are empty in the tsv files at the session level.
This could be due to the fact that the columns `DXCHANGE` and `DXCURREN` in `DXSUM_PDXCONV_ADNIALL.csv` are all empty for ADNI3, and that the new column `DIAGNOSIS` should be used instead.
I will ask the question at https://groups.google.com/g/adni-data to have the confirmation and then we should change the converter.

**Comment by alexandreroutier** [comment]
Answer from the [ADNI forum](https://groups.google.com/g/adni-data/c/AqxGPd2fUK8):

> Hi Elina,
>
> Yes, how diagnosis was captured in the database varied according to the phase of ADNI. So, for ADNI-1, DXCURREN was used, while in ADNI-GO/2, DXCHANGE was used. You have correctly identified the variable that has diagnosis for ADNI-3 (DIAGNOSIS).
>
> Another option, so you don’t need to merge across multiple variables, is to use the ADNIMERGE file (“Key ADNI tables merged into one table”), which contains diagnosis at each visit for all ADNI participants, along with a variety of other commonly used variables.
>
> Danielle
