### ISSUE TITLE
Replacing unmaintained `BrainStat`

### ISSUE THREAD

**Issue by NicolasGensollen** [aramis-lab/clinica#1269]
The `StatisticSurface` pipeline used to rely on the Matlab toolbox `SurfStat` but was re-written a couple years ago to rely on a pure Python implementation of it called `brainStat` instead (see #669).
The reason for this was that `SurfStat` was both unmaintained and more difficult to work with as it was relying on Matlab.

Recently, trying to update our dependencies, especially `numpy` (see #1263), I realized that bumping `Numpy` to v2 breaks  things in `brainStat`. Having a look at it, it seems like we are now facing the same issue as we were with `SurfStat`: last commit was more than 2 years ago, issues have been unanswered for years, and PR not reviewed (including this fix I made two years ago: https://github.com/MICA-MNI/BrainStat/pull/293 which I completely forgot about...).

It doesn't look like this is going to change in a near future. I think we need to do something in order to drop `brainstat` from our dependencies. A possibility could be to rewrite the pipeline to rely on more robust and maintained packages (`nilearn` being at the top of my mind), but that would require some work.

**Comment by zihuaihuai** [comment]
Hey there! I'm back to maintaining BrainStat now. Just finished merging your previous pull request about data types. Don't give up on us! Feel free to bring more issues and pr!

**Comment by NicolasGensollen** [comment]
Hi @zihuaihuai 

Yes, I saw some recent action on Brainstat which is great news. 🎉 
I'm gonna close this issue then.
