### ISSUE TITLE
missing anat and func

### ISSUE THREAD

**Issue by heena-manglani** [aramis-lab/clinica#130]
Hi clinica developers,

In the adni to bids conversion, anatomical and functional data for some participants is not being converted to BIDS format, despite existing nifti files. Any suggestions? 

Thanks in advance for the help!

-Heena

**Comment by alexandreroutier** [comment]
Hello @heena-manglani,

Thank you for your interest in Clinica and sorry about this issues.

Could you follow instructions given in Issue #128 and give me, for 2 ADNI participants, the case where T1w and/or fMRI is/are missing.

Best,
Alex

**Comment by omar-rifai** [comment]
Hi there, 

As this issue has been inactive for a while and with no response from the OP, I will close it down. Please do not hesistate to ask a question on the [forum](https://groups.google.com/g/clinica-user) or open a new issue if need be.

Regards, 

Omar El Rifai
