### ISSUE TITLE
Changes in diagnosis in recent versions of ADNI

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinica#131]
Hello,

We found out that some diagnoses of ADNI participants changed in the recent version of raw data of ADNI. This could lead to  reproducibility issues.
We are currently discussing with the ADNI data user group to better understand these changes.

**Comment by alexandreroutier** [comment]
Link to conversation: https://groups.google.com/g/adni-data/c/d-RWbWtXrQ8
