### ISSUE TITLE
[CI] OASIS-to-BIDS data to update

### ISSUE THREAD

**Issue by AliceJoubert** [aramis-lab/clinica#1323]
Following issue #1314, OASIS-to-BIDS CI data needs to be updated to use `oasis_cross-sectional-5708aa0a98d82080.xlsx` instead of `oasis_cross-sectional.csv`.

**Comment by NicolasGensollen** [comment]
We probably should open these data related issues in the `clinica_data_ci` repo instead of here. We can still track them in the project management section.
