### ISSUE TITLE
A query of the name of the columns in NIFD's  idaSearch_all.csv file

### ISSUE THREAD

**Issue by Ya-Lin-Huang** [aramis-lab/clinica#134]
Hello,

I got an Error message when I was trying to convert NIFD dataset to BIDS format (see Pic 1.).
I checked the scripts bylines and I found out that the format of the value (i.e. line[5] in Pic 2. ) seemed not matched to the scripts.
In my idaSearch_all.csv the column in position 5 is "weight", while the value is expected to be related to the date.
May I ask what's the information of the position 5?  Is it the acquired date of the scan? 
(Pic 3. shows the column and the value in the idaSearch I downloaded from the NIFD dataset following the instruction on clinica.run)  

Pic 1: 
![image](https://user-images.githubusercontent.com/60729741/95054904-24f2ac00-0725-11eb-80fd-5151c5d86be4.png)
Pic 2: 
![image](https://user-images.githubusercontent.com/60729741/95055011-4358a780-0725-11eb-8856-ebc5cd594585.png)
Pic 3: 
![image](https://user-images.githubusercontent.com/60729741/95055851-77809800-0726-11eb-8ecc-414bc9ae61f3.png)

Thank you and hope you have a nice day!
Lily

**Comment by omar-rifai** [comment]
NIFD converter had been put aside for a while. @ghisvail is this issue still relelvant? Otherwise please feel free to close.
