### ISSUE TITLE
Enhancement of `pet-linear` pipeline

### ISSUE THREAD

**Issue by ravih18** [aramis-lab/clinica#1346]
**Is your feature request related to a problem? Please describe.**
FDG-PET from some datasets (for instance ADNI) sometimes contain negative values that can impact the behavior of `pet-linear` pipeline.

**Describe the solution you'd like**
In order to deal with it, I would like to modify the `pet-linear` pipeline and add the following steps:
- Clip PET images in input and set the value of all the voxel below 0 to 0.
- Erase the background of the image at the end of the pipeline (set the background to 0 using a dilated mask of the MNI).

**Comment by NicolasGensollen** [comment]
Hi @ravih18 

Thanks for opening this.
I don't think there is an issue with you implementing this. I'm simply wondering whether these operations should be implemented as options that the users would choose to apply or not, or whether these would be added to the pipeline with no control given to the users.
Both have pros and cons and it really depends on whether keeping the negative values and the original background could be useful/desirable to users or not.
Do you have an opinion on that ?
