### ISSUE TITLE
Question abot ADNI converter

### ISSUE THREAD

**Issue by fyb99** [aramis-lab/clinica#1358]
**Description**
What is happening?

**Pipeline**
Which Clinica's Pipeline is concerned?
- t1-volume
...

**Converters**
Which Clinica's converter is concerned?

- adni-to-bids

Hi, I use the clinica converter to  preprocess the ADNI dataset, I have successfully run the BIDS converting and get the nii.gz files. How to do the following steps, like matching the Brain MRIs to the MN152 template, normalizing the volume, cropping the brain region and so on.

**Comment by AliceJoubert** [comment]
Hello ! 

If I understand your situation correctly : you just converted ADNI T1 images using our converter and now you want to process them. You can look up our documentation to see what suits your situation the best : [t1-linear](https://aramislab.paris.inria.fr/clinica/docs/public/dev/Pipelines/T1_Linear/), [t1-volume](https://aramislab.paris.inria.fr/clinica/docs/public/dev/Pipelines/T1_Volume/), [freesurfer](https://aramislab.paris.inria.fr/clinica/docs/public/dev/Pipelines/T1_FreeSurfer/).

Best,

**Comment by fyb99** [comment]
Hi, I use the t1-linear to convert the volume to the MN152 template, however, it reports an error, ''2024-10-28 18:45:09,460:ERROR:[Error] Clinica could not find ants software: the N4BiasFieldCorrection command is not present in your PATH environment. '' How to fix that? I can successfully run the converting step.

**Comment by fyb99** [comment]
The full logs are given here
UserWarning: The existing CAPS dataset, located at /mnt/data2/yibing/image-tabular/data/ADNI/raw_MRI/ADNI_CAPS has a name '1c74c702-8f20-4abc-946d-3fbfaefddb5f' different from the new name '7be4fff1-fbdc-4b06-abde-a7b57a5600df'. The old name will be kept.
  warnings.warn(message, warning_type)
2024-10-28 20:09:52,267:WARNING:Could not determine if /mnt/data2/yibing/image-tabular/data/ADNI/raw_MRI/ADNI_CAPS is a CAPS or BIDS directory. Clinica will assume this is a CAPS directory.
2024-10-28 20:09:54,674:ERROR:Clinica faced error(s) while trying to read files in your BIDS directory.
Clinica encountered 1 problem(s) while getting T1w MRI:
        * (sub-ADNI007S6255 | ses-M024): No file found

**Comment by AliceJoubert** [comment]
Clinica outputs this error when it cannot find a T1 file for t1-linear. Did you check if you had a corresponding image in the  ses-M024 directory for sub-ADNI007S6255 ? 

Also, what version of clinica are you using ?

**Comment by fyb99** [comment]
Hi, I double check it and find thisn file does not exist, I use the adni-to-bids converter and it seems some sample are not successfully converted because the failure of passing QC or other reasons. How to fix it? Will it work if I delete the empty dir in the BIDS dir and then rerun the command? Or how could I specify the converting samples that are currently available by setting some parameters?

**Comment by fyb99** [comment]
I delete the empty dir and it seems the command works now.

<img width="748" alt="image" src="https://github.com/user-attachments/assets/98120d36-37ab-4994-9677-bb0edf73c13b">

**Comment by AliceJoubert** [comment]
Removing the empty folder was the right solution. The screen shot shows that this time clinica did not find any error in the inputs and will run the pipeline. The logs you get are the informative logs from the pipeline.  Now the pipeline is working and you just need to wait until completion of the pipeline to get the results in your output folder.
