### ISSUE TITLE
Problems when using t1-linear

### ISSUE THREAD

**Issue by fyb99** [aramis-lab/clinica#1361]
**Description**
What is happening?

**Pipeline**
- t1-linear

**Converters**
Which Clinica's converter is concerned?
- adni-to-bids

Hi, recently I use t1-linear pipeline to align the samples to MN152 space. If I use another software to remove the skull, does it matter if I firstly perform skull removing and send the output to the t1-linear pipeline? I am not very sure whether t1-linear only supports the raw brain-mri as input, will the alignment accuracy be affected if I use skull-removed MRIs as input?

**Comment by AliceJoubert** [comment]
Hello, 

The processes in T1-linear uses the MNI template as a reference, which is not skull stripped. To avoid any unwanted interaction I would say to perform brain extraction after running our pipeline.

Best,
