### ISSUE TITLE
CreateMergeFile test is failing

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinica#153]
**Describe the bug**
There is a problem with the test `CreateMergeFile`. Probably due to a new version of a dependency.

**To Reproduce**
1. Run `nonregression/test_run_iotools.py`

**Expected behavior**
CreateMergeFile should pass, there is an assertion problem.

**Comment by omar-rifai** [comment]
Fixed with release v0.4.0 (the reference merged file needs to be updated due to a change in column names)
