### ISSUE TITLE
Bug induced by --nprocs of deeplearning-prepare-data

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinica#154]
**Describe the bug**
When using `deeplearning-prepare-data`, if `--nprocs` option was not given the program will ask the following question
`How many threads do you want to use? If you do not answer within 15 sec, default value of 79 will be taken. Use --n_procs argument if you want to disable this message next time.`
However when launching it with `sbatch` with SLURM after 15 secondes the program did not begin.

The output of the command is the following (many times):
```
How many threads do you want to use? If you do not answer within 15 sec, default value of 79 will be taken. Use --n_procs argument if you want to disable this message next time.
Your answer must be a positive integer.
How many threads do you want to use? If you do not answer within 15 sec, default value of 79 will be taken. Use --n_procs argument if you want to disable this message next time.
Your answer must be a positive integer.
```

**To Reproduce**
1. Create a bash script to launch clinica run deeplearning-prepare-data (without the option --nprocs).
2. Launch with sbatch.
3. See messages on standard output.

**Expected behavior**
The program is never launched and asking the number of threads indefinitely.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by mdiazmel** [comment]
The same behavior to fix when running the `t1-linear` pipeline!

**Comment by alexandreroutier** [comment]
Since the question is implemented in `clinica/pipelines/engine.py`, I think this affects any pipeline :(

**Comment by mdiazmel** [comment]
It should be nice to have an option to remove this behavior, something like `--not-ask` . This will be useful when Clinica is launched within a script!

**Comment by alexandreroutier** [comment]
When it was discussed long time ago, if `--n_procs` was not specified, the message would be displayed with a 15 seconds of timeout. If not answered, all available resources are taken after the timeout but some reason, using a job scheduler like Slurm blocks this mechanism :(

However, the use of `--n_procs` flag does not trigger this message which should be equivalent to `--not-ask `. Unless you want `--not-ask ` to take all possible resources 🤔 

@14thibea: Would you prefer an options that set all possible resources (i.e. what was Clinica suposed to do after 15 seconds ^^) or giving `--n_procs N` suits your needs?

**Comment by mdiazmel** [comment]
> When it was discussed long time ago, if `--n_procs` was not specified, the message would be displayed with a 15 seconds of timeout. If not answered, all available resources are taken after the timeout but some reason, using a job scheduler like Slurm blocks this mechanism :(

This is a tricky behavior that depends greatly on the variables used to launch the job in the slurm script (`--ntasks`, `--cpus-per-task`, etc.). Since the implementation in Clinica uses the `cpu_count` function from the `multiprocessing` module, I would say that `--cpus-per-task` must be the same that the argument `--n_procs`, but it's clearly redundant (and it could be source of confusion).

> However, the use of `--n_procs` flag does not trigger this message which should be equivalent to `--not-ask`. Unless you want --not-ask to take all possible resources 🤔

It's not equivalent! `--n_procs` needs to precise a value while `--not-ask` doesn't.

**Comment by omar-rifai** [comment]
@alexandreroutier  isn't the issue global to all pipelines with -np?

**Comment by ghisvail** [comment]
I am closing this issue since the `yes` flag is implemented for interactive use and the dlpd pipeline is now gone.

There is one issue remaining which is the propagation of interactive parameters to multiple pipelines, but it should be addressed in another issue with more relevant context.
