### ISSUE TITLE
Python and clinica version error

### ISSUE THREAD

**Issue by MariaCrespoEchevarria** [aramis-lab/clinica#156]
**Describe the bug**
I have a problem while installing clinica in Ubuntu. I need to download the version 0.3.8 of clinica.  On the one hand, If I use the version of python 3.7 I manage to get the clinica 0.3.8 version. However, the ejecution is killed when collecting torch>1.0 when creating the enviroment for the installation. On the other hand, if I use the version 3.8 of python automatically the version 0.3.7 of clinica is installed which causes errors in the format file in the conversion from ADNI to BIDS.

**To Reproduce**
Steps to reproduce the behavior for clinica version 0.3.8:
1. conda create --name clinicaEnv python=3.7
2. conda activate clinicaEnv
3. pip install clinica

Steps to reproduce the behavior for clinica version 0.3.7:
1. conda create --name clinicaEnv python=3.8
2. conda activate clinicaEnv
3. pip install clinica

**Expected behavior**
Correct installation of clinica version 0.3.8

**Desktop (please complete the following information):**
 - OS: Ubuntu 64 bits (runned in Oracle VM)
 -Terminal

**Comment by mdiazmel** [comment]
Hi, 

Thanks for your interest in Clinica!

We prefer that you use the most recent version of Clinica (0.3.8, to this date). One alternative to try finding whats going on is to create the environment and try to install PyTorch before installing Clinica:
```
conda create --name clinicaEnv python=3.7
conda activate clinicaEnv
pip install torch torchvision
pip install clinica
```
Try to target `torch==1.7.1`, that's the version that we use in our tests. Pytorch installation command can be different depending on your architecture, [check here in case of doubts](https://pytorch.org/get-started/locally/).

Let us known if the problem persists.

Best,

**Comment by MariaCrespoEchevarria** [comment]
Hello again,
I have managed to install the torch. However, now I keep having problems with the installation. I try to follow the suggestions that the program gives me but I am afraid that I am making mistakes. Would it be possible to make a video-conference with you, so that you can help me?
Thanks in advance,
Maria

**Comment by mdiazmel** [comment]
Hi @MariaCrespoEchevarria ,

In order to help you, please tell us what is the error you get, once the installation steps above are done.

**Comment by MariaCrespoEchevarria** [comment]
Hello,
Here I list you some of the problems I have now:

1-After installing clinica, for using the converter it is asking me to download a folder (MRIcron) and to added to the path, and so I did it. However, still it is not able to find it. In the same way, the program suggests downloading the version of 2016 but on the Internet only the version of 2019 is available.  Could this fact generate a problem? I think so, because, the program has asked for dcm2nii and dcm2niix but in the platform where MRIcron has been downloaded only dcm2niix file is available (version 2019).

2- Also, I have realised that the virtual enviroment is created by default in anaconda3 instead of miniconda3 and I do not know if this affects in the final output.

3- Finally, I would also want to let you know that I want to make the conversion to BIDS of T1_weigthed, fMRI and dwi images. I have read in the documentation of clinica that the conversion of these images generate some known errors (T1->does not generate an output file, dwi->wrong files and dimensions and fmri->does not generate an output file). You can find more information in the following link: http://www.clinica.run/doc/Converters/ADNI2BIDS/

**Comment by MariaCrespoEchevarria** [comment]
Hello,
Here I list you some of the problems I have now:

1-After installing clinica, for using the converter it is asking me to download a folder (MRIcron) and to added to the path, and so I did it. However, still it is not able to find it. In the same way, the program suggests downloading the version of 2016 but on the Internet only the version of 2019 is available. Could this fact generate a problem? I think so, because, the program has asked for dcm2nii and dcm2niix but in the platform where MRIcron has been downloaded only dcm2niix file is available (version 2019).

2- Also, I have realised that the virtual enviroment is created by default in anaconda3 instead of miniconda3 and I do not know if this affects in the final output.

3- Finally, I would also want to let you know that I want to make the conversion to BIDS of T1_weigthed, fMRI and dwi images. I have read in the documentation of clinica that the conversion of these images generate some known errors (T1->does not generate an output file, dwi->wrong files and dimensions and fmri->does not generate an output file). You can find more information in the following link: http://www.clinica.run/doc/Converters/ADNI2BIDS/

**Comment by mdiazmel** [comment]
I will try to provide an solution/answer for your problems:

1. `dcm2nii` it's an old software used to convert dicom images into nii format. It's available [here](https://www.nitrc.org/frs/?group_id=152). If you're in a Linux machine you can download an old version (e.g., MRIcron 4/2011 Linux (32-bit GTK1)), unzip it and copy the binary named `dcm2nii` to a folder visible on your PATH variable (for example the same location where `dcm2niix` is).

2.  Miniconda3 is a subset of Anaconda3. If you have installed Anaconda3 in your machine it should be ok.

3. There are issues in the conversion of some subjects of ADNI into BIDS due to problems during the acquisition of the dataset. These are only a few subjects among the hundreds of samples in the database. This information is published for the users of the tool for clarity and transparency.

**Comment by omar-rifai** [comment]
Hi there, 

As this issue has been inactive for a while and with no response from the OP, I will close it down. Please do not hesistate to ask a question on the [forum](https://groups.google.com/g/clinica-user) or open a new issue if need be.

Regards, 

Omar El Rifai
