### ISSUE TITLE
ADNI-to-bids convertion only generates .tsv files as an output

### ISSUE THREAD

**Issue by itsasnearangoa** [aramis-lab/clinica#157]
**Description**
I have a problem when executing the adni-to-bids conversion because only .tsv files are generated as an output. I have read the documentation of clinica and I have realised that my problem is the initial structure of the ADNI dataset I downloaded from ADNI. I have searched this example https://github.com/aramis-lab/clinica#example, and my dataset does not look like that. The structure of the ADNI dataset looks like the figure I have attached in the this clinica forum: https://groups.google.com/g/clinica-user/c/6eIiMcD7ONw .
How can I make to download the database in the required structure? Or is there a way to change the structure once it is downloaded?

**Converters**

- adni-2-bids

**Used images**

-T1
-DWI
-FMRI

Thank you in advance!

**Comment by 14thibea** [comment]
Hi,

Thank you for your interest in clinica!
I just checked your architecture and rerun the converter with data freshly donwloaded and it worked for me, could you please give us the command line you typed?
Also are all the TSV files created or only the `participants.tsv` + the files in the `conversion_info` folder?

**Comment by itsasnearangoa** [comment]
Hi, 
Thank you for answering. The command I have typed in order to do the conversion is the following:
`clinica convert adni-to-bids '/home/itsasne/Documents/dataset_directory' '/home/itsasne/Documents/clinical_data_directory' '/home/itsasne/Documents/bids_directory'`
The content that this command generates is the ./bids_directory is the following:
.
├── conversion_info
│   ├── amyloid_pet_paths.tsv
│   ├── dwi_paths.tsv
│   ├── fdg_pet_paths.tsv
│   ├── flair_paths.tsv
│   ├── fmri_paths.tsv
│   ├── pib_pet_paths.tsv
│   ├── t1_paths.tsv
│   └── tau_pet_paths.tsv
└── participants.tsv
And inside the conversion_info file these are the generated files:
.
├── amyloid_pet_paths.tsv
├── dwi_paths.tsv
├── fdg_pet_paths.tsv
├── flair_paths.tsv
├── fmri_paths.tsv
├── pib_pet_paths.tsv
├── t1_paths.tsv
└── tau_pet_paths.tsv

**Comment by 14thibea** [comment]
Based on the image you sent on Google, I guess that there is an error in the path to images, it should be:
`clinica convert adni-to-bids '/home/itsasne/Documents/dataset_directory/ADNI' '/home/itsasne/Documents/clinical_data_directory' '/home/itsasne/Documents/bids_directory'`

**Comment by itsasnearangoa** [comment]
Hi,
Thanks to your suggestion the conversion has succesfully done, but the problem I have now is that no .json files have been generated. I supose that this is because in the ADNI directory I have no .xml files together with the .nii files. These .xml files are in another folder called metadata, which I downloaded from ADNI together with the .nii images. Is there any way of generating those missing .json files that has to be present in the BIDS folder?
Thank you so much.

**Comment by 14thibea** [comment]
Actually, we chose not to generate most of the .json files as all the columns are already explained in the Excel files here https://github.com/aramis-lab/clinica/tree/dev/clinica/iotools/data
More explanation will be available and also some BIDS errors will be rectified as soon as https://github.com/aramis-lab/clinica/pull/144 will be merged.

**Comment by omar-rifai** [comment]
Hello, 

I will now close this issue. If you have additional questions please do not hesitate to use the [forum](https://groups.google.com/g/clinica-user) or open a new issue.

Regards, 

Omar El Rifai
