### ISSUE TITLE
!clinica run t1-linear ./OasisBids_example ./OasisCaps_example --n_procs 2  crashed

### ISSUE THREAD

**Issue by cquptzhanglin** [aramis-lab/clinica#158]
I get a error.

The pipeline will be run on the following 4 image(s):
	sub-OASIS10016 | ses-M00,
	sub-OASIS10109 | ses-M00,
	sub-OASIS10304 | ses-M00,
	sub-OASIS10363 | ses-M00,
The pipeline will last approximately 6 minutes per image.

[04:30:58] The t1-linear pipeline finished with errors.

CAPS outputs were not found for 4 image(s):
	sub-OASIS10016 | ses-M00
	sub-OASIS10109 | ses-M00
	sub-OASIS10304 | ses-M00
	sub-OASIS10363 | ses-M00

Error details can be found by opening the crash file(s) with the following command(s):
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-040600-zhanglin-n4biascorrection.a3-2c61f0a3-cdb0-4722-9b55-590bd81aadd8.pklz
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-041643-zhanglin-n4biascorrection.a1-44684502-6137-4a9a-9a52-5db1b78b7c12.pklz
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-041911-zhanglin-n4biascorrection.a2-66a3b618-10d0-4ffd-a76d-5b5460c23c46.pklz
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-042810-zhanglin-n4biascorrection.a0-31ec04f6-aaa7-4e79-bf09-027881d81dba.pklz
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-040927-zhanglin-n4biascorrection.a3-4a8559dd-abb3-4fa0-9835-58caebea7b5e.pklz
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-042010-zhanglin-n4biascorrection.a2-3ec2fedc-5a78-4147-bd39-f2961395a19c.pklz
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-042012-zhanglin-n4biascorrection.a1-96218ca2-baa0-4999-8251-82e233cf2d18.pklz
- nipypecli crash  /home/zhanglin/tmp/AD-DL/NoteBook/crash-20210119-043056-zhanglin-n4biascorrection.a0-ed5a2e05-40f1-4ff6-b370-50654aea7d76.pklz

If your pipeline crashed due to lack of space of network issues, re-run the pipeline with the working directory (-wd /tmp/tmphc7ikj94).
Known issues are displayed here: http://www.clinica.run/doc/InteractingWithClinica/#known-issues
Otherwise, you can delete it.

[clinica.log](https://github.com/aramis-lab/clinica/files/5833517/clinica.log)

**Comment by mdiazmel** [comment]
Hi, 

Have you tried to run the pipeline with the option `--working_directory`?

Otherwise, try to allocate more RAM memory for your job (I can see from the log that only 3.44Gb are available). If this doesn't work, reinstall ANTs, the software providing the function `n4biascorrection`.

**Comment by cquptzhanglin** [comment]
As you said,I add the memory,it worked,thanks







------------------ Original ------------------
