### ISSUE TITLE
PIPELINE FINISHED WITH ERRORS

### ISSUE THREAD

**Issue by ccastri** [aramis-lab/clinica#188]
Hi everybody!
After I did the BIDS conversion I tried to do the t1-volume pipeline but I had that error. I looked at that folder and truly I didn't have any .nii file here. So What I need to do to find that missing file from this subject?

![Error_T1_Volume](https://user-images.githubusercontent.com/68607137/113527777-3148ac00-9584-11eb-95ac-1e196fb5d94a.jpg)

In the meantime I decided to delete the missing subject folder and then ran the T1 Volume pipeline but still having errors. Also I tried the Freesurfer pipeline too, after I deleted the subject empty folder,  with a subject_tsv file (to take into account only the folders that having subject sessions) but again I have a storage error related to the working directory as you all can see bellow. Te upper terminal shows the results of executing T1-Volume and de lower terminal shows the results for Freesurfer pipeline.

It was correct to delete the sub-ADNI016S0769 | ses-M86 or do that can cause some crashed when the pipelines are running?

![Question](https://user-images.githubusercontent.com/68607137/113527824-5fc68700-9584-11eb-84b7-91e18a81d76b.jpg)

**Comment by ccastri** [comment]
Thanks, I'll be completly placed if you all guys can help me

**Comment by omar-rifai** [comment]
Hello Camilo, sorry for the late reply. I have followed up your question in the [google group](https://groups.google.com/g/clinica-user/c/jVbHSFcASIQ). I will close this issue as it seems to be a environment specific concern.

Do not hesitate to let us know if you're still having problems or reopen an issue if need be. 

Regards
