### ISSUE TITLE
Some questions about adni-to-bids

### ISSUE THREAD

**Issue by asd567** [aramis-lab/clinica#238]
What is happening?
This is the first time for me and my team to use the clinica.

I have downloaded a large range datas about ADNI from the websit.

But when I looked the unzip files, I was lost in thought. There were too many datas! I thought that should I merge the datas according to matedata, or should I use `clinica convert adni-to-bids NEW1/ADNI clinical_data BIDS -m T1` and `clinica run adni-to-bids NEW2/ADNI clinical_data BIDS -m T1` and so on? 

Thought twice, I decided to use the second method to convert the datasets.  Luckly, it seemed that I had convert the datasets successfully. However, when I run `clinica run t1-volume BIDS CAPS label`, some wrong happened in the 1/4 `t1-volume-tissue-segmentation`: CAPS outputs were not found for some image(s) . I had a issue https://github.com/aramis-lab/clinica/issues/219, the answer was the MATLAB or SPM12 version error. 

I thought twice, and then decided to merge a single test called 4449 , and run `convert` successfully, and run `t1-volume `successfully! I was shocked! 

According to my experience, should I merge so many ADNI datasets? 

Hopefully to receive the replay

Thanks

**Comment by omar-rifai** [comment]
Hi @asd567, 

What exactly do you mean by "merging" tests? Are you merging files of different subjects? Same subject with different modality?

Regards,

**Comment by asd567** [comment]
Hello @omar-rifai  ,
The "merging " means that :
Some ADNI dataset after unzip and looks like:
NEW1
|
|---ADNI
|---|
|---|---├── 027_S_0074
|---│   ├── 3-plane_localizer
|---│   │   ├── ...
|---│   │   └── 2015-02-13_09_52_18.0
|---│   │       └── S249015
|---│   ├── ADNI_Brain_PET__Raw
|---│   │   ├── ...
|---│   │   └── 2019-01-23_15_54_06.0
|---│   │       └── I1119527
|---│   ├── ADNI_Brain_PET__Raw_AV45
|---│   │   ├── ...
|---│   │   └── 2015-04-01_16_18_44.0
|---│   │       └── I481838
|---│   ├── Axial_DTI
|---│   │   ├── ...
|---│   │   └── 2019-01-24_10_35_14.0
|---│   │       └── S788290
|---│   ├── ...
|---├── 041_S_1260
......

NEW2
|
|---ADNI
|---|
|---|---├── 027_S_0074
|---│   ├── 3-plane_localizer
|---│   │   ├── ...
|---│   │   └── 2017-02-13_09_52_18.0
|---│   │       └── S249015
|---│   ├── ADNI_Brain_PET__Raw
|---│   │   ├── ...
|---│   │   └── 2016-01-23_15_54_06.0
|---│   │       └── I1119527
|---│   ├── ADNI_Brain_PET__Raw_AV45
|---│   │   ├── ...
|---│   │   └── 2013-04-01_16_18_44.0
|---│   │       └── I481838
|---│   ├── Axial_DTI
|---│   │   ├── ...
|---│   │   └── 2012-01-24_10_35_14.0
|---│   │       └── S788290
|---│   ├── ...
|---├── 041_S_1260
...

The same ID (041_S_1260 for example) 's files in different directorys.

**Comment by omar-rifai** [comment]
adni-to-bids will select the images to "convert" according to the rules detailed [here](https://aramislab.paris.inria.fr/clinica/docs/public/PR-221/Converters/ADNI2BIDS/). Perhaps the reason you were not successful in your first attempt was because the folder you converted did not contain the images from the modality you wanted?

**Comment by asd567** [comment]
@omar-rifai  Thank you for replay. I gusee so, I used the BIDS-validator tool and find that my BIDS file is not a BIDS struct.  But I am confused that I used the command `clinica convert adni-to-bids ADNI clinicaldata BIDS` to convert all modalities .

**Comment by ghisvail** [comment]
I guess you tried running the converter on each of the unzipped folder separately, as opposed to first downloading and unzipping all the imaging data to a single location and run the converter once there. I believe we only support the latter.

**Comment by asd567** [comment]
@ghisvail 
Thank your for explaining. I downloaded datasets from the ADNI website in 10 zipping files and unzippng them to different files. I will unzipping them again to a single location. But I am wondering that there are so many files in the same name, will them do not confilct? 
Thanks

**Comment by asd567** [comment]
@ghisvail 
I am very appreciate it that you can understand and give me the addvice.  I have some questions about ADNI-DATA downloaded from the ADNI-website. The data were devided into 5 zipped files and have an another file named MATEDATA, should I unzipping this file to the same location which I unzipping the ADNI-DATA ? I will appreciate it . 
Thanks

**Comment by ghisvail** [comment]
> should I unzipping this file to the same location which I unzipping the ADNI-DATA ?

You should have one folder with the unzipped clinical data (a large list of CSV files), and one folder with the unzipped content of each zip file downloaded from the collection interface. I believe the root folder for each archive is `ADNI`.

I'll update the documentation to with a paragraph on the preparation of the dataset folder.
