### ISSUE TITLE
dwi-preprocessing error : CAPS outputs were not found some image(s):problem reading coef-file out_warp.nii.gz

### ISSUE THREAD

**Issue by asd567** [aramis-lab/clinica#240]
Hi, there!

When I run command line `clinica run dwi-preprocessing-using-t1 BIDS CAPS`, some error happened:

CAPS outputs were not found for some image(s).
Implementation on which image(s) failed will appear soon.

There have a crashed file, the detail:

File: /home/limpid/Desktop/test1/crash-20210512-200645-limpid-CoeffComp.a1-e09775c3-ea98-426c-a2cb-af52b3f544d8.pklz
Node: dwi-preprocessing-using-t1.SusceptibilityDistortionCorrection.CoeffComp
Working directory: /tmp/tmp0zo6jwt5/dwi-preprocessing-using-t1/SusceptibilityDistortionCorrection/ce645544a9132dc951176054999cde695cb10b4c/CoeffComp

Node inputs:

args = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
in_file = <undefined>
knot_space = <undefined>
out_file = <undefined>
out_format = spline
out_jacobian = <undefined>
output_type = NIFTI_GZ
reference = /home/limpid/Desktop/test1/BIDS/sub-CLNC0113/ses-M00/anat/sub-CLNC0113_ses-M00_T1w.nii.gz
warp_resolution = <undefined>
with_affine = <undefined>
write_jacobian = False

Traceback: 
Traceback (most recent call last):
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 829, in _run_interface
    self.raise_exception(runtime)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 760, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
fnirtfileutils --in=/tmp/tmp0zo6jwt5/dwi-preprocessing-using-t1/SusceptibilityDistortionCorrection/ce645544a9132dc951176054999cde695cb10b4c/combine_warp/out_warp.nii.gz --outformat=spline --ref=/home/limpid/Desktop/test1/BIDS/sub-CLNC0113/ses-M00/anat/sub-CLNC0113_ses-M00_T1w.nii.gz --out=out_warp_coeffs.nii.gz
Standard output:

Standard error:
fnirtfileutils: Problem reading coef-file /tmp/tmp0zo6jwt5/dwi-preprocessing-using-t1/SusceptibilityDistortionCorrection/ce645544a9132dc951176054999cde695cb10b4c/combine_warp/out_warp.nii.gz
Return code: 1

I opened the terminal and got into the error file path.  The out_warp.nii.gz was not empty, I opened this file and there had only a file named out_warp.nii, which was not empty . I clicked the file trying to open it, but the remind : have no software to open this.

I wonder if I am not install the third-party completely. 

Thanks,

**Comment by Mrsirovo** [comment]
I have the same question.
To solve the question, I went through the project's issues, but all failed.
Will it locate in enviroment? I have tried it in different machines and got the same result.

**Comment by asd567** [comment]
Hello, 
       Thanks for your replay. As you tried every methodes and got the same results, I don't think this error are the environment or software-version problems. Just about one hour ago, I successfully run `t1-volume` as I issued https://github.com/aramis-lab/clinica/issues/219 without changing Matlab or SPM12 version. Just because I looked the output file names in my terminal, I found a file was missing and delated this. 
Based on those, I think is the problems maybe about BIDS files. 
Yours,
asd567

**Comment by asd567** [comment]
@Mrsirovo I have the same error when I run the `dti-preprocessing-using-t1`command line . This time I checked the BIDS structer whith using https://github.com/bids-standard/bids-validator,  and I am not the BIDS file. Would you please check your BIDS file struct using this tool ? I will appreciate it.
Thanks

**Comment by asd567** [comment]
@Mrsirovo 
Hi, 
I using fsl to check the out_wrap.nii.gz, and the fsl shows that this .nii is very dim, I think this may be the question about read out_warp.nii.gz filed.   Based on this I'm assuming the error files would be in the same dim in your  tmp/* files.

But what happened can result in this  still a question. 

I will closed this issue and open a new issue.

Cheers

**Comment by asd567** [comment]
@Mrsirovo  
Hi , 
I find the solution in the googl-groups, it's a reason about fsl-version. FSL5.0 is okey, but FSL6.0 is not.

**Comment by asd567** [comment]
@Mrsirovo 
Hello, do you solve the dwi-preprocessing-* problem? I am stuck in the dwi-dti now. 
Ragards
