### ISSUE TITLE
Separate interactive prompts from logging

### ISSUE THREAD

**Issue by ghisvail** [aramis-lab/clinica#262]
There are places in our code where interactive prompts and logging are mixed which is not great. See the `data_handling` module for examples.

That's where a proper CLI library such as `click` or `typer` would shine, since you can explicitly dissociate what's interactive from what's logging.

For now, all interactive message must be set to `warning` otherwise it won't be displayed at the default verbosity level.

**Comment by omar-rifai** [comment]
Handled by PR#[301](https://github.com/aramis-lab/clinica/pull/301)
