### ISSUE TITLE
Compulsory/optional CL arguments not clear

### ISSUE THREAD

**Issue by ravih18** [aramis-lab/clinica#264]
**Is your feature request related to a problem? Please describe.**
When using deeplearning-prepare-data pipeline, some optional arguments are compulsory depending on main arguments (for instance `suvr_reference_region` or `acq_label` when modality is `pet-linear`). However if these arguments are missing, the output is not clear, only the list of options of the pipeline is displayed.

**Describe the solution you'd like**
A solution could be the use of subparser to make some optional arguments compulsory depending on other options. This could be solved with the use of `typer` for Clinica CLI (futur CLI update).

**Comment by ghisvail** [comment]
Another alternative would be to define different subcommands (one per modality?), instead of composing multiple subparsers of command options.

**Comment by ghisvail** [comment]
Fixed in #329
