### ISSUE TITLE
ADNI to BIDS conversion error. (In raw data file)

### ISSUE THREAD

**Issue by BanDoong** [aramis-lab/clinica#268]
**Describe the bug**

**Not all converted from  ADNI file to Bids.
(Only few subjects are converted)** 

**To Reproduce**
**1. Get RAW data from ADNI
2. Convert RAW ADNI data to BIDS
3. Clinica can't find the paths of the ADNI ( I tested T1w)**

**Expected behavior**

**you should remove not only this line,
https://github.com/aramis-lab/clinica/blob/d6fb831d1f9edfd3a7b067915bcbb91869091b80/clinica/iotools/converters/adni_to_bids/adni_modalities/adni_t1.py#L196

but also this line.

https://github.com/aramis-lab/clinica/blob/96571e0d1ad5f5bfe61648e80b4fd7f1c0f4c833/clinica/iotools/converters/adni_to_bids/adni_modalities/adni_t1.py#L234

and then return function original_image.**

**Screenshots**

**Desktop (please complete the following information):**
 **- OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] : Safari
 - Version [e.g. 22] : clinica 0.4.1**

**Additional context**

**Comment by ghisvail** [comment]
Hi @BanDoong, thanks for providing those details.

What led you to find which line to delete? Could you provide a specific subject ID for which there is a significant difference before and after your proposed fix? Would you like to submit a PR for it eventually?

Cheers,

**Comment by omar-rifai** [comment]
Hi @BanDoong, 

I had replied to your original google forum post [here](https://groups.google.com/g/clinica-user/c/YzgTYBylDOE). Please let me know if the issue linked addresses your concern.

Regards,

**Comment by omar-rifai** [comment]
@BanDoong, I think it's a fair point and we could consider including this choice as an option. However, we can not accept the [PR](https://github.com/aramis-lab/clinica/pull/270) in its current state as it would completely change the behavior (instead of having this as an option).
