### ISSUE TITLE
Verify Freesurfer 7 compatibility

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#278]
Some pipelines in Clinica rely on Freesurfer (version v.6.x). As the current stable version at time of writing is 7.1, it would be good to verify that there the pipelines are compatible with the latest release so that the dependencies can be upgraded.

**Comment by MatthieuJoulot** [comment]
Hi. It would seem that FastSurfer needs FreeSurfer to work, and that it only works with FreeSurfer 6.0 atm (See FAQ at the end of this page: https://github.com/Deep-MI/FastSurfer/blob/master/Tutorial/Complete_FastSurfer_Tutorial.ipynb).
Apparently, FreeSurfer is used for the preprocessing steps, as suggested in this paper (https://www.sciencedirect.com/science/article/pii/S1053811920304985), at 2.2. (Methodogy -> Datasets).

**Comment by ghisvail** [comment]
Good point. We'd need an extra version check for FreeSurfer 6 when using the FastSurfer option.

**Comment by ghisvail** [comment]
FreeSurfer version 7.2 is now available and has no breaking changes with the 7.1 series according to the release notes.

**Comment by ghisvail** [comment]
Compatibility with FreeSurfer 7 and onwards will be verified in [pydra-freesurfer](https://github.com/aramis-lab/pydra-freesurfer), which Clinica will eventually benefit from transitively.

Closing as this will not be actively worked within Clinica anymore.
