### ISSUE TITLE
Fast Surfer as an option

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#282]
[Fastsurfer](https://github.com/Deep-MI/FastSurfer) seems to be an performance-improved alternative to Freesurfer. As a first step towards potentially replacing Freesurfer, we need to implement Fastsurfer as an option that can be activated through the command line.

**Comment by ghisvail** [comment]
As pointed in #278, FastSurfer only works for FreeSurfer 6 at the moment. In addition to providing this option, we'd need an extra version check.

**Comment by ghisvail** [comment]
@MatthieuJoulot or @omar-rifai could you confirm whether this issue will be further worked on? My understanding was that it was a dead end  and [this thread](https://github.com/aramis-lab/clinica/discussions/537) was the ultimate outcome from the investigation.

**Comment by ghisvail** [comment]
To be revisited at a later stage once the project gathers enough maturity.
