### ISSUE TITLE
clinica iotools center-nifti does not work for symlinks

### ISSUE THREAD

**Issue by anbai106** [aramis-lab/clinica#290]
**Describe the bug**
This may not be a bug, but deserve to give a warning. 
I have tried to center my images using this command: **_clinica iotools center-nifti bids_dir bids_dir_centered_**

However, I got this error: 
![Screenshot from 2021-06-20 16-49-47](https://user-images.githubusercontent.com/16743978/122687977-7c6b7600-d1e7-11eb-843f-b77350aee6f9.png)

I looked into the issue. It seems to be due to this function:
**_/gpfs/fs001/cbica/home/wenju/Project/clinica/clinica/iotools/utils/data_handling.py     632 center_all_nifti copytree(join(bids_dir, f), join(output_dir, f))_**

Where copytree by default sets **symlinks=False**. My **bids_dir** is indeed symlinks.  

Should we raise an warning for this? 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
commit 677465c22aabcffd7df324ebeb75b49f1a310d9c
Author: Mauricio DIAZ <mauricio.diaz@inria.fr>
Date:   Tue Dec 29 21:06:45 2020 +0100

    Prepare release 0.3.8

**Comment by anbai106** [comment]
Bids_dir is symbol-inked, ie the nifti images

**Comment by ghisvail** [comment]
What about the output BIDS directory? Is it symlinked too?

**Comment by anbai106** [comment]
No the directory is not

**Comment by ghisvail** [comment]
We do not intend to support symlinks officially, since it's not obvious the BIDS spec was designed to support this use case and it may lead us to an array of unforeseen corner cases. My general recommendation would be to avoid feeding BIDS datasets with symlinks to Clinica or other tools that do not **explicitly** advertise support for them.
