### ISSUE TITLE
Replace the class loader functionality

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#294]
A class loader functionality which was historically in Clinica (but ununsed up until now) has been removed in [PR275](https://github.com/aramis-lab/clinica/pull/275). We could replace it with a more idiomatic 'Click' mechanism if it is needed.

**Comment by ghisvail** [comment]
I believe third-party extension of Clinica is an exciting topic, but won't come back in the form of a class loader. Instead, we would likely come up with a proper plugin architecture for the relevant parts of Clinica which may benefit from runtime extensions.
