### ISSUE TITLE
Lost shell completion completion after argparse -> Click migration

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#307]
**Describe the bug**
Shell completion is currently deactivated. For instance, `clinica run <TAB>` does not display the list of pipelines with autocompletion.

Tested on 

**Additional context**
I noticed that instructions for having shell completion is explained on their documentation:
- 7.0 version : https://click.palletsprojects.com/en/7.x/bashcomplete/
- 8.0 version: https://click.palletsprojects.com/en/8.0.x/shell-completion/
(Changelog indicates some changes between 7 and 8 version)

I don't know if these changes are easy to do but in any case, the Wiki should be updated for the moment: https://aramislab.paris.inria.fr/clinica/docs/public/latest/Installation/#activation-of-the-clinica-environment

Alex

**Comment by ghisvail** [comment]
[Instructions](https://click.palletsprojects.com/en/8.0.x/shell-completion/#enabling-completion) for enabling shell completion are the same for v7 and v8 onwards. Feel free to have a try.
