### ISSUE TITLE
Nipype outputs are displayed on default

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#313]
**Describe the bug**
Nipype outputs are now displayed on default which was not the case in the past

**To Reproduce**
Steps to reproduce the behavior: run any pipeline with default flags.

**Expected behavior**
Only the subjects that are run or finished (see #219 for example screenshot)

**Screenshots**
<img width="1280" alt="Nipype-Outputs" src="https://user-images.githubusercontent.com/24808663/124268848-642a1e00-db3a-11eb-87e6-9b6f603d0f6d.png">

**Comment by ghisvail** [comment]
It should be a matter of updating [setup_logging](https://github.com/aramis-lab/clinica/blob/5fe56a1442de72a38b8717bec5a91cb514300067/clinica/cmdline.py#L23) to configure the nipype logging accordingly.

**Comment by ghisvail** [comment]
Maybe even better would be to have a separate `setup_nipype` function responsible for [configuring nipype](https://nipype.readthedocs.io/en/0.11.0/users/config_file.html#enabling-logging-to-file) to our liking.
