### ISSUE TITLE
t1-linear method does nothing

### ISSUE THREAD

**Issue by V-Krause** [aramis-lab/clinica#315]
I have successfully converted my ADNI data to BIDS using the adni-to-bids method and would now use the t1 linear method to apply the pet linear method later.

After a few small error fixes, I now have the problem that everything should seem to work correctly, but nothing comes of it.

The pipeline has been running for hours now, but there is neither a result nor any visible progress. I have often tried only one picture, which should take 6 minutes, but even after a few hours there was no result.

![image](https://user-images.githubusercontent.com/54623188/124469097-380cd800-dd9a-11eb-9832-9a7e32fc1d37.png)

In this picture I tried it with 24 Images, but it stuck at this point.

So what can I do?

**Comment by V-Krause** [comment]
Of course.

I tried it with:
    subject            033_S_1016
    session            M48

**Comment by omar-rifai** [comment]
Hello, 
I can not seem to reproduce the issue. T1-linear seems to run fine on this subject-session (in about 6 minutes) with Clinica 0.4.1 (latest) Is this the version you are using?

Regards

**Comment by V-Krause** [comment]
Hello,
yes I use Clinica 0.4.1. 

But I have to say that I had some problems getting ANTs to work and before that I always got the error that the n4biascorrection is not recognized. But I got this fixed after a clean reinstallation. However, I have the assumption that it might be because of that. Maybe you can give me a quick guide on what steps to take to get this installed properly? Or should I do a complete reinstallation of all?

Thank you for your fast answers!

**Comment by mdiazmel** [comment]
Hi,

> But I have to say that I had some problems getting ANTs to work and before that I always got the error that the n4biascorrection is not recognized. But I got this fixed after a clean reinstallation. However, I have the assumption that it might be because of that. Maybe you can give me a quick guide on what steps to take to get this installed properly? Or should I do a complete reinstallation of all?

Yes, it seems that there is a problem with your ANTs installation. Try to uninstall it and install it again. We're currently proposing a conda recipe to facilitate ANTs installation in Conda Forge. In the meanwhile, you can try to install it [using our Channel](https://anaconda.org/aramislab/ants):
```
 conda install -c aramislab ants 
```
(inside the Conda environment where you installed Clinica).

Best,

**Comment by V-Krause** [comment]
@mdiazmel 
The installation work fine, but now I get this error and don't know what I do wrong, because ANTs is a folder.

![image](https://user-images.githubusercontent.com/54623188/124588619-4e2d9d80-de59-11eb-9f0f-65b01a4e9e52.png)

**Comment by mdiazmel** [comment]
> @mdiazmel
> The installation work fine, but now I get this error and don't know what I do wrong, because ANTs is a folder.

To set the environment variables for ANTs, you need to point it out to the place where Conda install the package, for your case it should be something like this:
```
ANTSPATH="/home/vinc/minconda3/env/clinicaEnv/bin"
export PATH=${ANTSPATH}:${PATH}
```
after doing this, you can verify if the binaries of ANTs are installed by running `antsRegistration -h`, from the command line, for example.

**Comment by V-Krause** [comment]
Okay, I reinstall my whole VM, because of some issues and now that worked. But now I have the problem with the n4biascorrection again.

![image](https://user-images.githubusercontent.com/54623188/124647958-e8f89d00-de96-11eb-8f14-cca2353338a2.png)

In the previous VM I fixed it with an extra path for the n4biascorrection. Is there another solution or is that correct?

**Comment by mdiazmel** [comment]
Could you show us the content of the one of the nipype logs, please?
(Type in your terminal `nypipecli crash  /home/vinc/crash-xxxxxxxxxxxxxxxxxxxxxxxxxx.pklz`)

**Comment by V-Krause** [comment]
Here is the first.

![image](https://user-images.githubusercontent.com/54623188/124672669-b7dc9480-deb7-11eb-8ddc-08fb7bfa4fda.png)

![image](https://user-images.githubusercontent.com/54623188/124672707-c88d0a80-deb7-11eb-8d43-d5e8fc13013d.png)

**Comment by omar-rifai** [comment]
I think the issue is the space character you have in your path as indicated by the path `N4BiasFieldCorrection`is trying to look in. Try to rename your folder to "ADNI_REST" and it should solve your problem !

**Comment by V-Krause** [comment]
Okay now it works. Thanks to everyone for the quick and helpful answers!

**Comment by omar-rifai** [comment]
Great! Gl with your study.
