### ISSUE TITLE
There is no roi option in deep learning-prepare-data pipeline.

### ISSUE THREAD

**Issue by BanDoong** [aramis-lab/clinica#318]
**Description**
What is happening?

There is no roi option in deep learning-prepare-data pipeline.
(I already check the python file as well.)

Is there any reasons about that??

**Pipeline**
Which Clinica's Pipeline is concerned ?
E.g.
- pet-volume
- t1-linear
- t1-volume
...

deeplearning-prepare-data

**Comment by omar-rifai** [comment]
Hello @BanDoong, 

Are you talking about the ROI (Region of Interest) option?  Which version of Clinica are you using? 

Thanks

**Comment by BanDoong** [comment]
My Apologies for the late response.

Yes I am talking about ROI options. 
My Clinica Version is 0.4.1

Best Regards,

**Comment by BanDoong** [comment]
I think this is came from this line was added

https://github.com/aramis-lab/clinica/blob/72ff267194648d27e2a11b9c5c4724f3ba0abee3/clinica/pipelines/deeplearning_prepare_data/deeplearning_prepare_data_pipeline.py#L121

But deeplearning_prepare_data_cli.py didn't changed.

https://github.com/aramis-lab/clinica/blob/72ff267194648d27e2a11b9c5c4724f3ba0abee3/clinica/pipelines/deeplearning_prepare_data/deeplearning_prepare_data_cli.py#L18

**Comment by omar-rifai** [comment]
Hello @BanDoong, it is a feature that has been merged into the dev branch of Clinica but that has not yet been released. We are planning a release by the end of the month.

**Comment by BanDoong** [comment]
Thanks for your response.
If the new version released, I will try that one.
