### ISSUE TITLE
T1-volume doesn't launch because of unexpected keyword argument

### ISSUE THREAD

**Issue by MatthieuJoulot** [aramis-lab/clinica#320]
**Describe the bug**
When launching the t1-volume pipeline, an error is immediately raised, saying that __init__ got an unexpected keyword argument "bids_directory".

**To Reproduce**
1. Launch the t1-volume pipeline

**Expected Behaviour**
Computing the t1-volume.

**Screenshots**
<img width="1404" alt="screenshot cli pb" src="https://user-images.githubusercontent.com/85217698/125260285-7bb69300-e300-11eb-9b90-e2702ddcaec1.png">

**Comment by ghisvail** [comment]
Could you try changing these lines in [here](https://github.com/aramis-lab/clinica/blob/dd0b2b1f207d6c49740107b1a4a3d1ca0fa12fce/clinica/pipelines/t1_volume/t1_volume_cli.py#L86-L87) from:

```python
bids_directory=bids_directory,
caps_directory=caps_directory,
``` 

to

```python
bids_directory,
caps_directory,
```

and report whether the first part of the pipeline is executed.

**Comment by MatthieuJoulot** [comment]
I tried just now. It gives me the same error as before but with the unexpected keyword argument being the tissue class (the argument right after caps_directory.
<img width="982" alt="Screenshot 2021-07-12 at 11 28 11" src="https://user-images.githubusercontent.com/85217698/125265081-c4704b00-e304-11eb-88fb-8acd4ba49af8.png">

I did the same thing and replaced
` tissue_classes=tissue_classes,`
with
`tissue_classes,`

which gives me a different error:
<img width="982" alt="Screenshot 2021-07-12 at 11 28 53" src="https://user-images.githubusercontent.com/85217698/125265345-0c8f6d80-e305-11eb-8db5-f71904c0589b.png">

**Comment by ghisvail** [comment]
I found the issue. I am preparing a fix for you to test.

**Comment by ghisvail** [comment]
Could you try #321 please?

**Comment by MatthieuJoulot** [comment]
#321 fixed the issue ! Thanks

**Comment by ghisvail** [comment]
Same fix needs to be done for `t1-freesurfer-longitudinal`. Can you do it?

**Comment by MatthieuJoulot** [comment]
Yes no problem !
