### ISSUE TITLE
[DEV] Creation of scan_file crashes for AIBL

### ISSUE THREAD

**Issue by MatthieuJoulot** [aramis-lab/clinica#330]
**Describe the bug**
When launching the aibl-to-bids converter, the pipeline crashes during the scan files creation step

**To Reproduce**
1.  Launch the aibl-to-bids converter with any files.

**Screenshots**
<img width="1007" alt="Screenshot 2021-07-15 at 17 34 32" src="https://user-images.githubusercontent.com/85217698/125815956-04f6e4cc-4165-4b4b-b6dc-f5b02718ae1f.png">

**Comment by omar-rifai** [comment]
Handled in PR#[336](https://github.com/aramis-lab/clinica/pull/336)
