### ISSUE TITLE
[DEV] OASIS crashes during the creation of the sessions files

### ISSUE THREAD

**Issue by MatthieuJoulot** [aramis-lab/clinica#331]
**Describe the bug**
OASIS crashes because it tries to write the sessions files at a precise location, "your/path/out/bids/subject", "out/bids" being hard-written, and this path does not necessarily exist.

**To Reproduce**
1. Launch OASIS with any images with a path different that "out/bids"

**Screenshots**
<img width="1007" alt="Screenshot 2021-07-15 at 18 43 20" src="https://user-images.githubusercontent.com/85217698/125825792-43cc02db-ac91-4823-9d09-3c8d3741dd66.png">

**Comment by omar-rifai** [comment]
Solved in PR#[335](https://github.com/aramis-lab/clinica/pull/335)
