### ISSUE TITLE
T1-linear for pet-linear?

### ISSUE THREAD

**Issue by V-Krause** [aramis-lab/clinica#332]
Quick Question:

I want to run the pet-linear pipeline. The description says that I have to run the t1-linear pipeline beforehand ("You need to have performed the t1-linear pipeline on your T1-weighted MR images."). Everything worked without any problems. But where do I say that I want to include this in the PET pipeline? As soon as I execute this, it only requires the normal T1w MRI images from the BIDS directory. 
Do I have to add something to the command or where are the preprocessed MRI images used?

**Comment by omar-rifai** [comment]
Hello @V-Krause,

When running your pet-linear pipeline, you need to point to the same CAPS directory as the one used for the outputs of t1-linear. Clinica will be able to recognize the data it needs from that CAPs directory and append to it the output from pet-linear.

Hope this answers your question! 

Cheers,

**Comment by V-Krause** [comment]
Yes, that's exactly what I wanted to know,

Thank you!
