### ISSUE TITLE
Merge tsv tool for FS longitudinal

### ISSUE THREAD

**Issue by DarioSARACINO** [aramis-lab/clinica#333]
Hello,
I use to run the `t1-freesurfer-longitudinal` pipeline, but I've seen that there is no way to pick up its `.tsv`outputs and automatically merge them in a big dataframe. The Clinica iotool `create-merge-tsv`apparently runs only with the outputs of the `t1-freesurfer` pipeline for cross-sectional processing. Would it be possible to adapt it to fit the longitudinal pipeline too?
Best regards,
Dario

**Comment by omar-rifai** [comment]
Is being developed in PR#[360](https://github.com/aramis-lab/clinica/pull/360)
