### ISSUE TITLE
Clinca crash

### ISSUE THREAD

**Issue by Izard00** [aramis-lab/clinica#344]
**Description**
What is happening?
Clinica crash

**Pipeline**
Which Clinica's Pipeline is concerned ?
E.g.
- pet-volume
- t1-linear
- t1-volume
...

**Converters**
Which Clinica's converter is concerned ?
E.g.
- adni-2-bids
- aibl-2-bids
- oasis-2-bids
...
ADNI-2-BIDS

**I/O tools**
Which Clinica's tool is concerned ?
E.g.
- merge-tsv
- create-subjects-visits
- check-missing-modalities

Hi, I was running ADNI-2-BIDS and encounter this issue, would like to know how to solve it.

Thanks

Clinica crashed reading clinical data file: CDR.csv
<img width="1245" alt="Screen Shot 2021-07-26 at 10 13 18 AM" src="https://user-images.githubusercontent.com/40375416/127013802-19c101fb-400f-4008-89c1-df27f369f29d.png">

**Comment by omar-rifai** [comment]
Hello Izard! Which version of Clinica are you using? You can verify using `clinica --version'

Can you please also give me a the list of subjects you were trying to convert? 

Thanks!

**Comment by Izard00** [comment]
Hi, sorry for the late reply, we had a server down issue and just solve it now.
The clinical version is 0.4.1
And the list attached 
[subjects.txt](https://github.com/aramis-lab/clinica/files/6925164/subjects.txt)

Thanks

**Comment by omar-rifai** [comment]
We have released a new version of Clinica: 0.5.0 a couple of weeks ago. Would you mind upgradingto see if the problem persists?

Thank you !

**Comment by Izard00** [comment]
Thanks, will try it out and we are checking from the data side also.
