### ISSUE TITLE
Link to developer instructions is dead

### ISSUE THREAD

**Issue by MatthieuJoulot** [aramis-lab/clinica#357]
**Describe the bug**
The link to developer instructions is 404 not found.

**To Reproduce**
Go to this page https://aramislab.paris.inria.fr/clinica/docs/public/latest/Atlases/ and click  on "developer instructions" like below.

**Screenshots**
<img width="668" alt="Screenshot 2021-07-30 at 17 51 39" src="https://user-images.githubusercontent.com/85217698/127679418-0afd4525-80b6-45af-b524-3c2b2360b12f.png">

**Comment by ghisvail** [comment]
Indeed, the link should be `https://aramislab.paris.inria.fr/clinica/docs/public/latest/Installation/#installation`, not `https://aramislab.paris.inria.fr/clinica/docs/public/latest/Installation/#install-clinica`

**Comment by omar-rifai** [comment]
I'm not sure this is the right link. Or at least it seems the page is missing some instructions to download Clinica through the source code

**Comment by ghisvail** [comment]
We are missing a section for development puproses, i.e. doing `git clone ...`, `pip install requirements-dev.txt`, `pip install -e .`

**Comment by ghisvail** [comment]
My bad, we have got one, it's just hidden in an info box. I don't think that's the right place to put it as it's not easily discoverable and we don't get a linkable anchor for it.

**Comment by ghisvail** [comment]
Default:

<img width="702" alt="Capture d’écran 2021-08-02 à 11 25 28" src="https://user-images.githubusercontent.com/1964655/127838259-dd89b5b2-db16-489c-b243-41213ec774d7.png">

On click:

<img width="701" alt="Capture d’écran 2021-08-02 à 11 25 50" src="https://user-images.githubusercontent.com/1964655/127838264-7e1663ec-cce3-47f0-b132-ff0f0ebd3ffd.png">

**Comment by omar-rifai** [comment]
Ah true! I had missed that too! I agree it's better to have it as a separate subsection instead of an info box.

**Comment by ghisvail** [comment]
I'll take care of it

**Comment by ghisvail** [comment]
See https://github.com/aramis-lab/clinica/pull/358

We could then use the new anchor `#developer-instructions`
