### ISSUE TITLE
adni-2-bids use original T1 dicom data instead of processed T1 data

### ISSUE THREAD

**Issue by vnckppl** [aramis-lab/clinica#368]
**Description**
I wonder if it is already possible to force adni-2-bids to use original dicom T1 data instead of the processed T1 data (Gradwarp, B1-inhomogeneity corrected and N3 bias field corrected images).

On your webpage (https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/) you write:

> **T1-weighted MRI** When several scans are available for a single session, the preferred scan (as identified in MAYOADIRL_MRI_IMAGEQC_12_08_15.csv) is chosen. If a preferred scan is not specified then the higher quality scan (as defined in MRIQUALITY.csv) is selected. If no quality control is found, then we choose the first scan for the visit. Gradwarp, B1-inhomogeneity corrected and N3 bias field corrected images are selected. 

**Converters**
Which Clinica's converter is concerned ?
- adni-2-bids

**Example**
I downloaded original data for ADNI GO Subject 002_S_1261. After unzipping the data, I have a folder with the following structure:

```
   |-MPRAGE
   |---2011-03-14_16_12_08.0
   |-----S101646
   |-MPRAGE_SENSE2
   |---2011-03-14_16_23_34.0
   |-----S101641
```

These folders contain dicom images that convert to T1 images (this step was verified).

However, when I run adni-2-bids on this structure:

```
clinica \
     convert \
     adni-to-bids \
     --subjects_list ~/adni2bids_sublist.txt \
     "${idir}" \
     "${cdir}" \
     "${odir}" \
     --modalities T1
```

No T1 images are being reconstructed and the terminal shows the following output:

> Loading a subjects lists provided by the user...
> /output/ADNIGO_test
> Calculating paths of T1 images. Output will be stored in /output/ADNIGO_test/conversion_info/v0.
> More than 60 days for corresponding timepoint in ADNIMERGE for subject 002_S_1261 in visit ADNI3 Initial Visit-Cont Pt on 2017-03-15
> Timepoint 1: m96 - ADNI1 on 2015-06-02 (Distance: 652 days)
> Timepoint 2: m84 - ADNI1 on 2014-03-06 (Distance: 1105 days)
> We prefer m96
> [T1] Subject 002_S_1261 has multiple visits for one timepoint.
> More than 60 days for corresponding timepoint in ADNIMERGE for subject 002_S_1261 in visit ADNI3 Year 1 Visit on 2018-04-24
> Timepoint 1: m96 - ADNI1 on 2015-06-02 (Distance: 1057 days)
> Timepoint 2: m84 - ADNI1 on 2014-03-06 (Distance: 1510 days)
> We prefer m96
> [T1] Subject 002_S_1261 has multiple visits for one timepoint.
> More than 60 days for corresponding timepoint in ADNIMERGE for subject 002_S_1261 in visit ADNI3 Year 2 Visit on 2019-05-01
> Timepoint 1: m96 - ADNI1 on 2015-06-02 (Distance: 1429 days)
> Timepoint 2: m84 - ADNI1 on 2014-03-06 (Distance: 1882 days)
> We prefer m96
> [T1] Subject 002_S_1261 has multiple visits for one timepoint.
> No T1 image path found for subject 002_S_1261 in visit bl with image ID 62377
> No T1 image path found for subject 002_S_1261 in visit m06 with image ID 79126
> No T1 image path found for subject 002_S_1261 in visit m12 with image ID 109394
> No T1 image path found for subject 002_S_1261 in visit m24 with image ID 139510
> No T1 image path found for subject 002_S_1261 in visit m36 with image ID 171106
> No T1 image path found for subject 002_S_1261 in visit m48 with image ID 225357
> No T1 image path found for subject 002_S_1261 in visit m60 with image ID 296428
> No T1 image path found for subject 002_S_1261 in visit m72 with image ID 362927
> No T1 image path found for subject 002_S_1261 in visit m84 with image ID 418841
> No T1 image path found for subject 002_S_1261 in visit m96 with image ID 500243
> Paths of T1 images found. Exporting images into BIDS ...
> [T1] No path specified for 002_S_1261 in session bl 1/10
> [T1] No path specified for 002_S_1261 in session m36 2/10
> [T1] No path specified for 002_S_1261 in session m48 3/10
> [T1] No path specified for 002_S_1261 in session m12 4/10
> [T1] No path specified for 002_S_1261 in session m06 5/10
> [T1] No path specified for 002_S_1261 in session m72 6/10
> [T1] No path specified for 002_S_1261 in session m60 7/10
> [T1] No path specified for 002_S_1261 in session m96 8/10
> [T1] No path specified for 002_S_1261 in session m84 9/10
> [T1] No path specified for 002_S_1261 in session m24 10/10

(after this the command line continues with 'Creating modality agnostic files...' and finally finishes with 'Creating scans files...' without errors).

The generated csv file under `./ADNIGO_test_20210803_all/conversion_info/v0/t1_paths.tsv` shows the following relevant line:

| Subject_ID | VISCODE | Visit                       | Sequence                         |  Scan_Date | Study_ID | Series_ID | Image_ID | Field_Strength | Original | Is_Dicom | Path |
|------------|---------|-----------------------------|----------------------------------|------------|----------|-----------|----------|----------------|----------|----------|------|
| 002_S_1261 | m48     | ADNI1/GO Month 48           | MT1__N3m                         | 2011-03-14 |    32038 |    101641 |   225357 |            3.0 | False    | True     |      |

It seems to me that adni-2-bids does not use the raw T1 dicom data at all, only the processed and reconstructed T1 data.

I am now wondering if there is an option to have the converter tool use the original raw dicom files instead of the processed (Gradwarp, B1-inhomogeneity corrected and N3 bias field corrected images) T1 images?

**Comment by omar-rifai** [comment]
Hello @vnckppl,

Indeed, currently there is no option to convert the raw images and only the processed and reconstructed data (following the rules in the documentation) are converted. This has never really been an issue until now. Is there a particular reason you are looking to use the raw data instead of the corrected one?

Regards

**Comment by vnckppl** [comment]
Hi @omar-rifai,

I would like to use the unprocessed data and do all the inhomogeneity correction on the raw data instead of doing it on data sets were inhomogeneity correction has already been applied using different scanner software algorithms.

One other less important reason is that we downloaded the original data and not the preprocessed data. Downloading the additional data from ADNI will (again) take weeks. 

Thanks,

Vincent

**Comment by ghisvail** [comment]
> One other less important reason is that we downloaded the original data and not the preprocessed data.

That's what I was about to suggest, i.e. just create an ADNI collection without the preprocessed data and use this dataset instead.

What you are noticing is that despite the missing preprocessed data, the converter will not fallback to convert one of the available raw DICOM scan. Am I correct?

**Comment by vnckppl** [comment]
> What you are noticing is that despite the missing preprocessed data, the converter will not fallback to convert one of the available raw DICOM scan. Am I correct?

Exactly! Do you think it would be possible to enable this?

**Comment by omar-rifai** [comment]
Hello @vnckppl, 

Unfortunately it is currently not possible using Clinica. Our intention was primarily to make reproducible research easier. As such we want to make sure that the best possible images are used consistently.

Having this as an option might be conceivable but is not currently in the roadmap. 

Best
