### ISSUE TITLE
io.py prevents debugguer in pycharm to work 

### ISSUE THREAD

**Issue by arnaudmarcoux** [aramis-lab/clinica#37]
![Screen Shot 2019-09-24 at 18 28 28](https://user-images.githubusercontent.com/49677712/65530931-288c0a00-def9-11e9-9812-28e71d9c4d65.png)

Renaming the io.py file into something else solves the issue.

**Comment by alexandreroutier** [comment]
Hmm, the `io.py` file existed long before I added functions 🤔.

I will think on a possible renaming or splitting of the file, this will be
simpler.

Le mar. 24 sept. 2019 à 18:29, Arnaud Marcoux <notifications@github.com> a
écrit :

**Comment by alexandreroutier** [comment]
See PR #41.
