### ISSUE TITLE
clinica version 0.5.0 t1-linear registration bugs

### ISSUE THREAD

**Issue by BanDoong** [aramis-lab/clinica#388]
**Describe the bug**

I found T1-linear registration bugs

the command that I implemented is

**clinica run t1-linear bids caps --n_procs 9**

**Expected behavior**

**Screenshots**

<img width="1231" alt="스크린샷 2021-08-19 오후 4 08 12" src="https://user-images.githubusercontent.com/56647416/130023866-7f790bf2-763d-4034-8f31-68f7ab433098.png">

**Desktop (please complete the following information):**

Mac os

**Additional context**

**Comment by BanDoong** [comment]
I think it seems like mask is broken some part

mni_icbm152_t1_tal_nlin_sym_09c.nii

<img width="1231" alt="스크린샷 2021-08-19 오후 4 15 39" src="https://user-images.githubusercontent.com/56647416/130024841-cb32ce85-a92f-4e8a-8484-091a7a88a225.png">

**Comment by 14thibea** [comment]
Hi,

Indeed it seems that there is a problem with the template!
However the source file seems to be correct, maybe you had a problem during downloading the first time?
Could you please download it yourself [here](https://aramislab.paris.inria.fr/files/data/img_t1_linear/mni_icbm152_t1_tal_nlin_sym_09c.nii) and check that it is ok?
If the file is correct, could your replace your previous template with the new one and relaunch t1-linear?

Best,

**Comment by BanDoong** [comment]
This file is okay for t1-linear.
Thanks,

**Comment by omar-rifai** [comment]
Hello BanDoong, 

Are you still having this problem after downloading the file provided by @14thibea ?

Thank you.

**Comment by BanDoong** [comment]
Hello **Omar,**

It seems there is no error after downloading the file.

Thanks,
