### ISSUE TITLE
output of PET-Volume is noisy or smoothed

### ISSUE THREAD

**Issue by BanDoong** [aramis-lab/clinica#395]
**Description**
What is happening?

I runed the PET-Volume option.

clinica run pet-volume bids caps test tau cerebellumPons --pvc_psf_tsv ./caps/pvc_psf_tsv.csv
clinica run pet-volume bids caps test av45 cerebellumPons --pvc_psf_tsv ./caps/pvc_psf_tsv.csv

The outputs are different subjects by subjects.
The outputs are like this.

Some of outputs are like this.

033_S_6697 AV45
<img width="598" alt="image" src="https://user-images.githubusercontent.com/56647416/130908494-814891da-d4c4-48de-a877-4e13261fbcb2.png">

022_S_6013 AV1451
<img width="614" alt="image" src="https://user-images.githubusercontent.com/56647416/130908525-736bd530-6751-4214-adc6-654eae71d48b.png">

301_S_6591 AV1451
<img width="613" alt="image" src="https://user-images.githubusercontent.com/56647416/130908565-683878b3-c0b6-4405-a629-dd409c7c6d0d.png">

Some are very noisy or smoothed.

I was wondering that the smooth option is applied?
Some noisy image looks like didn't apply the smooth option.

Or This is simply because that PSF option value is not corrected?

The value that I applied about PSF is like this

<img width="398" alt="스크린샷 2021-08-26 오후 2 59 51" src="https://user-images.githubusercontent.com/56647416/130909078-e785ae9c-46fc-415e-a88c-772068715a4e.png">

Some of PET scanner doesn't have the PSF value.
So, I applied Similar value as scanner name.

Could you explain about the Scanner PSF value of it??
How can I know the PSF value?
(I already asked to ADNI but there is no answer about it.)

Thanks for your time and consideration.

Best Regards,

**Pipeline**
Which Clinica's Pipeline is concerned ?
E.g.
- pet-volume
- t1-linear
- t1-volume
...

PET-Volume

**Comment by omar-rifai** [comment]
Hello @BanDoong, 

Sorry for the late reply. As I have mentioned in a previous issue, the `psf` values are scanner and tracer specific. In the example you specified, you seem to be using the same values for `av45` and `tau` which seem to indicate that they may be potentially not correct. ADNI has details of which values to use in its metadata. Please let me know if you need further help. 

Regards
