### ISSUE TITLE
adni-to-bids converter wastes time on QC for participants not in collection

### ISSUE THREAD

**Issue by ghisvail** [aramis-lab/clinica#398]
## Context

This issue happens when converting collections with a reduced set of participants, for instance when doing triage on a bug for a specific participant.

## Description

The converter will analyze QC irrespective of the participants present in the input collection, which wastes a significant amount of time. Granted, users can restrict the set of participants being processed with a list via the `--subjects_list` option. However, our converters could be a bit more clever and only process the participants present in the input collection without further input.

In practice, this means indexing the input collection and filtering the list of participants appropriately prior to the conversion process. This is what's being done in the revamped NIFD converter for instance.

**Comment by NicolasGensollen** [comment]
@AliceJoubert I think this could be an interesting issue (a bit more involved than the previous ones) which is somehow related to QC.
Of course, there is no rush. Just tagging you to not forget about it.

**Comment by AliceJoubert** [comment]
Resolved with PR #1196 !
