### ISSUE TITLE
Adni-to-bids: Error on empty dataframe (missing ADNIMERGE data)

### ISSUE THREAD

**Issue by ghisvail** [aramis-lab/clinica#419]
## Context

I tried to reproduce the issue mentioned in this [comment](https://github.com/aramis-lab/clinica/issues/394#issuecomment-919458671), which claims the `adni-to-bids` converter is unable to process ADNI3 data.

## Triage

I have downloaded a collection for ADNI participant `002_S_1261` filtered on ADNI3 only (T1 and fMRI) and run the converter on it.

## Error

`AttributeError: 'DataFrame' object has no attribute 'session_id'` yielded from `(~df_subj_session.session_id.isin(["ses-Nv", "sc", None]))` in the ADNI utilities.

**Comment by omar-rifai** [comment]
It looks like the dataset is empty. Maybe an error in the subjects file? For a more informative error at this point, lines 723 and 726 could be inverted.

**Comment by ghisvail** [comment]
That's what I thought at first, but the log contains:

```
[...]
2021-09-15 11:42:31,556:INFO:Paths of T1 images found. Exporting images into BIDS ...
[...]
2021-09-15 11:42:33,465:INFO:Paths of FLAIR images found. Exporting images into BIDS ...
[...]
2021-09-15 11:42:34,167:INFO:Paths of fMRI images found. Exporting images into BIDS ...
[...]
```

**Comment by ghisvail** [comment]
Conversion works fine if I use a collection for the same participant filtered on ADNI2

**Comment by ghisvail** [comment]
Same for ADNI1-only

**Comment by ghisvail** [comment]
> It looks like the dataset is empty.

This is correct.

> Maybe an error in the subjects file? For a more informative error at this point, lines 723 and 726 could be inverted.

I think the issue lies somewhere else. Here is the shape of the dataframe before the call:

```
Columns: [RID, PTID, VISCODE, SITE, current_study, ORIGPROT, vitals_examdate, DX_bl, age, PTGENDER, PTEDUCAT, PTETHCAT, PTRACCAT, PTMARRY, APOE4, adni_fdg, adni_pib, adni_av45, adni_abeta, adni_tau, adni_ptau, cdr_sb, adas11, adas_praxis, ADASQ4, MMSE, neurobat_ravlt_immediate, neurobat_ravlt_learning, neurobat_ravlt_forgetting, neurobat_ravlt_perc_forgetting, neurobat_ldeltotal, neurobat_digitscor, neurobat_trabscor, FAQ, moca_moca, ecogpt_ecogptmem, ecogpt_ecogptlang, ecogpt_ecogptvisspat, ecogpt_ecogptplan, ecogpt_ecogptorgan, ecogpt_ecogptdivatt, ecogpt_ecogpttotal, ecogsp_ecogptmem, ecogsp_ecogptlang, ecogsp_ecogptvisspat, ecogsp_ecogptplan, ecogsp_ecogptorgan, ecogsp_ecogptdivatt, ecogsp_ecogpttotal, FLDSTRENG, FSVERSION, IMAGEUID, adni_ventricles_vol, adni_hippocampus_vol, adni_brain_vol, adni_entorhinal_vol, adni_fusiform_vol, adni_midtemp_vol, adni_icv, diagnosis, mPACCdigit, mPACCtrailsB, EXAMDATE_bl, CDRSB_bl, ADAS11_bl, ADAS13_bl, ADASQ4_bl, MMSE_bl, RAVLT_immediate_bl, RAVLT_learning_bl, RAVLT_forgetting_bl, RAVLT_perc_forgetting_bl, LDELTOTAL_BL, DIGITSCOR_bl, TRABSCOR_bl, FAQ_bl, mPACCdigit_bl, mPACCtrailsB_bl, FLDSTRENG_bl, FSVERSION_bl, Ventricles_bl, Hippocampus_bl, WholeBrain_bl, Entorhinal_bl, Fusiform_bl, MidTemp_bl, ICV_bl, MOCA_bl, EcogPtMem_bl, EcogPtLang_bl, EcogPtVisspat_bl, EcogPtPlan_bl, EcogPtOrgan_bl, EcogPtDivatt_bl, EcogPtTotal_bl, EcogSPMem_bl, EcogSPLang_bl, EcogSPVisspat_bl, EcogSPPlan_bl, EcogSPOrgan_bl, ...]
Index: []
```

No `session_id` column. The filter on `session_id` should work regardless of whether the dataframe is empty or not. However, in this particular case, the dataframe somehow does not have the right shape. Still investigating.

**Comment by ghisvail** [comment]
We use `ADNIMERGE` to compute the available sessions. The current version does not reference the ADNI3 data for this specific participant.

**Comment by ghisvail** [comment]
Best we can do for now is guard ourselves against empty dataframes returned from the `ADNIMERGE` processing. Maybe also reconsider whether `ADNIMERGE` should be considered the canonical source for listing sessions.
