### ISSUE TITLE
Better manage Conda environments in CI

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#476]
conda virtual environments associated with closed PRs are currently persistent on the CI machines which causes recurrent memory problems. A set-up that automatically deletes environment associated with merged (or closed ) PRs is needed.

**Comment by ghisvail** [comment]
> A set-up that automatically deletes environment associated with merged (or closed ) PRs is needed.

There are actually multiple issues associated with our current Conda env management:

- Reusability of build environments

We are currently caching our build environments for the duration of the PR lifecycle. This deviates from recommended CI practices which consider each build as a standalone process. Now that `poetry` is in place, perhaps we could revisit the need for keeping this behaviour.

- Autocleanup of build environments

That's exactly what Jenkins workspaces are for.

- Coupling of PR lifecycle with CI

This should be limited as much as possible. PR triggers builds, the rest (including cleanup) should be left to the CI process.

At least that's what I have read thus far.
