### ISSUE TITLE
Error with !clinica iotools merge-tsv d1bitOut  d1capout/participants.tsv

### ISSUE THREAD

**Issue by SonaLily** [aramis-lab/clinica#478]
Hello! I'm very grateful for all the help everyone has given me so far. I thought it would be good to open a new issue for this bug, as the old thread has been closed.
I have been able to successfully run : 
!clinica run t1-linear d1BIDSOut  d1CAPSout --n_procs  4
Then I continued to run:
!clinica iotools merge-tsv d1bitOut  d1capout/participants.tsv

And got following error message:
Traceback (most recent call last):
  File "/usr/local/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/clinica/cmdline.py", line 78, in main
    cli()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/clinica/iotools/utils/cli.py", line 255, in merge_tsv
    tracers_selection=pet_tracers_selection,
  File "/usr/local/lib/python3.7/dist-packages/clinica/iotools/utils/data_handling.py", line 160, in create_merge_file
    merged_df = merged_df.append(row_df)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 7751, in append
    sort=sort,
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/concat.py", line 287, in concat
    return op.get_result()
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/concat.py", line 503, in get_result
    mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy,
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/internals/concat.py", line 54, in concatenate_block_managers
    for placement, join_units in concat_plan:
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/internals/concat.py", line 561, in _combine_concat_plans
    raise ValueError("Plan shapes are not aligned")
ValueError: Plan shapes are not aligned

I'm using Google Colab

**Comment by SonaLily** [comment]
Just to add on to what I reported above, when I ran the IO tools listed below I got the respective error messages
Failed 1: !clinica iotools merge-tsv  d1BIDSOut d1BIDSOut/mergeOutput/
***********************
*** Clinica crashed ***
***********************

Exception type: InvalidIndexError
Exception value: Reindexing only valid with uniquely valued Index objects
Below are displayed information that were gathered when Clinica crashed. This will help to understand what happened if you transfer those information to the Clinica development team.

========================================================================
0 /usr/local/bin/clinica                                                            8    <module>          sys.exit(execute())
1 /usr/local/lib/python3.7/site-packages/clinica/cmdline.py                         652  execute           args.func(args)
2 /usr/local/lib/python3.7/site-packages/clinica/iotools/utils/data_handling_cli.py 166  run_command       tracers_selection=args.pet_tracers_selection,
3 /usr/local/lib/python3.7/site-packages/clinica/iotools/utils/data_handling.py     152  create_merge_file merged_df = merged_df.append(row_df)
4 /usr/local/lib/python3.7/site-packages/pandas/core/frame.py                       8970 append            sort=sort,
5 /usr/local/lib/python3.7/site-packages/pandas/util/_decorators.py                 311  wrapper           return func(*args, **kwargs)
6 /usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py              307  concat            return op.get_result()
7 /usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py              528  get_result        indexers[ax] = obj_labels.get_indexer(new_labels)
8 /usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py                3442 get_indexer       raise InvalidIndexError(self._requires_unique_msg)

Failed 2: !clinica iotools merge-tsv d1BIDSOut merge-tsv.tsv -caps d1CAPSout  


[Warning] The PYTHONPATH environment variable is not empty. Make sure there is no interference with Clinica (content of PYTHONPATH: /env/python).

***********************
*** Clinica crashed ***
***********************

Exception type: InvalidIndexError
Exception value: Reindexing only valid with uniquely valued Index objects
Below are displayed information that were gathered when Clinica crashed. This will help to understand what happened if you transfer those information to the Clinica development team.

==========================================================================
0 /usr/local/bin/clinica                                                            8    <module>          sys.exit(execute())
1 /usr/local/lib/python3.7/site-packages/clinica/cmdline.py                         652  execute           args.func(args)
2 /usr/local/lib/python3.7/site-packages/clinica/iotools/utils/data_handling_cli.py 166  run_command       tracers_selection=args.pet_tracers_selection,
3 /usr/local/lib/python3.7/site-packages/clinica/iotools/utils/data_handling.py     152  create_merge_file merged_df = merged_df.append(row_df)
4 /usr/local/lib/python3.7/site-packages/pandas/core/frame.py                       8970 append            sort=sort,
5 /usr/local/lib/python3.7/site-packages/pandas/util/_decorators.py                 311  wrapper           return func(*args, **kwargs)
6 /usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py              307  concat            return op.get_result()
7 /usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py              528  get_result        indexers[ax] = obj_labels.get_indexer(new_labels)
8 /usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py                3442 get_indexer       raise InvalidIndexError(self._requires_unique_msg)

Partial failed 3: !clinica iotools check-missing-modalities  d1BIDSOut d1BIDSOut/missing

***********************
*** Clinica crashed ***
***********************

Exception type: KeyError
Exception value: 'ses-M00'
Below are displayed information that were gathered when Clinica crashed. This will help to understand what happened if you transfer those information to the Clinica development team.

==========================================================================
0 /usr/local/bin/clinica                                                            8   <module>             sys.exit(execute())
1 /usr/local/lib/python3.7/site-packages/clinica/cmdline.py                         652 execute              args.func(args)
2 /usr/local/lib/python3.7/site-packages/clinica/iotools/utils/data_handling_cli.py 224 run_command          args.bids_directory, args.out_directory, args.output_prefix
3 /usr/local/lib/python3.7/site-packages/clinica/iotools/utils/data_handling.py     637 compute_missing_mods print_statistics(summary_file, len(subjects_paths_lists), sessions_found, mmt)
4 /usr/local/lib/python3.7/site-packages/clinica/iotools/converter_utils.py         40  print_statistics     ses_miss = missing_list[ses]["session"]
==========================================================================
==========================================================================

Documentation can be found here: https://aramislab.paris.inria.fr/clinica/docs/public/latest/
If you need support, do not hesitate to ask: https://groups.google.com/forum/#!forum/clinica-user
Alternatively, you can also open an issue on GitHub: https://github.com/aramis-lab/clinica/issues

Any help would be greatly appreciated!

**Comment by omar-rifai** [comment]
Hi @SonaLily,

Thank you for opening this issue. Can you please tell me which data-set you are using for running the tool? Is it a custom dataset or a public one (e.g ADNI, AIBL, etc?). If it is a public dataset, did you convert it to BIDS using clinica convert?

Thank you for your input.

**Comment by SonaLily** [comment]
Hello!
I used the public OASIS 3 dataset
I was able to convert it to BIDs using clinica without getting any errors with this command:
!clinica convert oasis3-to-bids xnatAii/d1 xnatAii/Oasis3ClinicalData xnatAii/d1BIDSOut
I also ran the ti-linear pipeline without any problems:
!clinica run t1-linear xnatAii/d1BIDSOut xnatAii/d1CAPSout --n_procs  2
Then I tried to run this command and got the errors above:
!clinica iotools merge-tsv d1bitOut d1capout/participants.tsv
The participants.tsv file is here if needed:
https://drive.google.com/drive/u/3/folders/1Uxhz-qJXzlO0LrkFlivhl07dBEh6-kGB
