### ISSUE TITLE
A question about freesurfer pipeline

### ISSUE THREAD

**Issue by theguardsgod** [aramis-lab/clinica#522]
how could I run "recon-all -autorecon1" in the freesurfer pipeline.

**Comment by MatthieuJoulot** [comment]
Hello,

If you want to run `recon-all -autorecon1` in the freesurfer pipeline, you can use the `recon_all_args` flag: `--recon_all_args="-autorecon1"`. You can find more details about it right here: https://aramislab.paris.inria.fr/clinica/docs/public/latest/Pipelines/T1_FreeSurfer/

Have a good day !

**Comment by MatthieuJoulot** [comment]
Hi, could you please tell us if the solution we provided answered your question, and if so, close this issue ?
Or if you have other questions do ask them ! 


Have a good day

**Comment by MatthieuJoulot** [comment]
I'll close this issue since there is no response.
