### ISSUE TITLE
Issues regarding the dwi-dti pipeline

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#545]
### Discussed in https://github.com/aramis-lab/clinica/discussions/543

<div type='discussions-op-text'>

<sup>Originally posted by **MatthieuJoulot** January 12, 2022</sup>
This discussion's purpose is to clarify the [dwi-dti pipeline](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Pipelines/DWI_DTI/) and the problems revolving around it.

1.  We use  MRtrix interfaces to generate the dti model and `FA`, `AD`, `RD`, `MD` and `DECFA` images. For this to work we start by converting the bval and bvec from fsl format to MRtrix using the [FSL2MRtrix](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.mrtrix.tensors.html#fsl2mrtrix) command. We then produce the tensors using [DWI2Tensor](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.mrtrix.preprocess.html#dwi2tensor) and, based on the tensor we can produce the different images by using [TensorMetrics](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.mrtrix3.utils.html#tensormetrics).
2. The images in step "1."  are then registered to MNI except the DECFA using ANTs's [RegistrationSynQuick](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.ants.html#registrationsynquick) and [ApplyTransform](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.ants.html#applytransforms)
3. The registered images in step "2." are thresholded and outputed using FSL's [Threshold](https://nipype.readthedocs.io/en/0.12.1/interfaces/generated/nipype.interfaces.fsl.maths.html#threshold)
4. The thresholded images in step "3."  are then used to produce statistics which are outputed.
5. The images produced by the step "1." are thresholded with FSL's Threshold and outputed

You can see the graph of the pipeline below.
![graph](https://user-images.githubusercontent.com/85217698/149124488-5f345e20-997e-4b07-a788-2a37db2dd8db.png)

A few potential problems come from this process.
1. The DECFA outputed by the fifth step is asymetric, whereas the DECFA from first step is not. The threshold seems to be responsible for this. It may have had a wrong effect on the other images as well. Also, since the thresholding from the third and the fifth step are the same, the numerical values produced may be wrong.

This is the DECFA image after the thresholding.
<img width="845" alt="Screenshot 2022-01-12 at 10 59 22" src="https://user-images.githubusercontent.com/85217698/149122296-03573eac-7646-4828-ac1c-00aa7a4fef98.png">

This is the DECFA image before the thresholding.
<img width="845" alt="Screenshot 2022-01-12 at 10 59 33" src="https://user-images.githubusercontent.com/85217698/149122496-e23e3cda-c1dd-41f8-96ec-f8bd01a2616a.png">

2. The reasons for these thresholdings is that MRtrix's DWI2Tensor can produce negative values. This issue is detailed [here](https://community.mrtrix.org/t/tensor2metric-works-not-well-to-give-negative-rd-ad-and-rd-inside-the-brain/1333/3) and [here](https://community.mrtrix.org/t/dwi2tensor-wrong-values/1860/17).

3. We can question the general compatibility of MRtrix and FSL as it is discussed [here](https://github.com/MRtrix3/mrtrix3/issues/1139) and [here](https://www.mrtrix.org/2016/04/15/bug-in-fsl-bvecs-handling/)

These issues make it difficult to trust the result outputed by the pipeline.</div>

**Comment by alexandreroutier** [comment]
Hi!

Thanks for spotting this issue!

The thresholding on the DEC-FA map is indeed incorrect: since the DEC-FA map is a particular 4D file, the applied thresholding will both affect the encoding direction and the FA. As a result, the colour representation of the direction vector will be affected.

To sum up this issue, a temporary bugfix would be to remove the threshold for the DEC-FA map since thresholding of FA/MD/AD/RD are correctly applied.

Alex

**Comment by MatthieuJoulot** [comment]
This issues has been solved in [PR#547](https://github.com/aramis-lab/clinica/pull/547) and will be closed.

**Comment by ghisvail** [comment]
Since the PR is not merged yet, we should probably leave this open for now.

**Comment by omar-rifai** [comment]
This issue is not related to the PR you mention. This issue was related to PR#547 which is indeed closed :)

**Comment by ghisvail** [comment]
My bad 😆

**Comment by ghisvail** [comment]
547 <--> 574 what are the odds
