### ISSUE TITLE
DWIPreprocessing - Replace `_preproc` suffix by `_dwi`

### ISSUE THREAD

**Issue by omar-rifai** [aramis-lab/clinica#614]
use `_dwi` as suffix instead of `preproc` for `bval` and `bvec` as in [example](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data)

**Comment by ghisvail** [comment]
We'd also need an additional `desc-preproc` entity as advised [here](https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html#examples) to distinguish the derived DWI filename from its original.
