### ISSUE TITLE
Find an alternative to ClinicaSurfStat

### ISSUE THREAD

**Issue by ghisvail** [aramis-lab/clinica#643]
Clinica implements its own wrapper around [SurfStat](https://math.mcgill.ca/keith/surfstat/), a MATLAB toolbox for statistical analysis of surface and volumetric data. MATLAB runtime management is a pain and `nipype` has been of great help to offset that pain away. That being said, the least amount of custom MATLAB code we maintain within Clinica the better.

There has been a new toolbox in the block called [BrainStat](https://www.biorxiv.org/content/10.1101/2022.01.18.476795v1.full.pdf), inspired by SurfStat, but also implemented in Python and available under a permissive license. This may be a good candidate for replacing `ClinicaSurfStat` in the long run.

**Comment by NicolasGensollen** [comment]
I agree that getting rid of MATLAB code is very valuable in the long run.
I don't know BrainStat well so I don't have a strong feeling about it being the right tool for the job or not.
By looking at the project, it is indeed relatively new and mostly developed by two contributors. I'm thus a little bit worried about its stability and its long term maintenance.
This might be a stupid question, but could other, more stable tools (like Nilearn for example which is already in Clinica's dependencies) also be good candidates for this? I can investigate if this is unclear.

**Comment by ghisvail** [comment]
> I don't know BrainStat well so I don't have a strong feeling about it being the right tool for the job or not.

They are explicitly targeting themselves as a `SurfStat` replacement in their publication, hence why it caught my interest whilst looking for an alternative. I am guessing the naming similarity is not an accident either.

> By looking at the project, it is indeed relatively new and mostly developed by two contributors. I'm thus a little bit worried about its stability and its long term maintenance.

Versus zero for our custom wrapper around SurfStat, which was one of the risks raised during last meeting.

> This might be a stupid question, but could other, more stable tools (like Nilearn for example which is already in Clinica's dependencies) also be good candidates for this? I can investigate if this is unclear.

I was looking for such tool and that's how I got to know `BrainStat`. If `nilearn` can implement this particular feature in Clinica, then that would be ideal.

I suspect porting `SurfStat` code to `BrainStat` may be easier since both are likely to share the same models and abstractions for analysing surfaces and volumes. We'd have to see what's already available in `nilearn` for comparison.

**Comment by omar-rifai** [comment]
For what it's worth, `Surfstat` seems to cite an old version of `BrainStat` as a source : 

>SurfStat is a Matlab toolbox for the statistical analysis of univariate and multivariate surface and volumetric data using linear mixed effects models and random field theory. It is inspired by Jason Lerch's [Thickness Statistics](http://wiki.bic.mni.mcgill.ca/index.php/ThicknessStatistics) written in [R](http://en.wikipedia.org/wiki/R_%28%20programming_language%29), **and Jonathan Taylor's BrainStat**, part of [NIPY](http://neuroimaging.scipy.org/), written in [Python](http://www.python.org/Python).

**Comment by omar-rifai** [comment]
Also, it seems the new Python version is an "[update](https://neurostars.org/t/mixed-effects-glm-with-python/20578/2)" w.r.t Surfstat

> fresh out there and potentially very helpful wrt this: [Brainstat 14](https://brainstat.readthedocs.io/en/master/index.html)! It’s a drastically updated version of surfstat and is now also available in python
