### ISSUE TITLE
Improve how BIDS data are grabbed

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#73]
Hi,

I faced the following use case: on a BIDS dataset, there was a subject with the following naming convention:
```text
└── sub-PPMI3532
    └── ses-M00
        └── anat
            └── sub-PPMI3532_ses-M00_T1w.nii.nii.gz
```
`.nii` extension was present twice. It didn't prevent Clinica from running but CAPS outputs will have bad naming conventions for pipelines using regexp substitutions with Dataskink e.g. `sub-PPMI3532_ses-M00_T1w.nii_segm-graymatter_probability.nii.gz` for `t1-volume-tissue-segmentation`. Of course, `t1-volume-create-dartel` will not grab this file.

To solve this issue, we need to improve the regexp when grabbing BIDS files to avoid this situation to occur.

Alex

**Comment by omar-rifai** [comment]
Will verify if the code checks for the modality type (`t1`). If it is the case, will make the changes to reject other modalities `T1w.nii`, otherwise, add that check.
