### ISSUE TITLE
Consider getting rid of nipy as a testing dependency

### ISSUE THREAD

**Issue by ghisvail** [aramis-lab/clinica#734]
Clinica currently depends on `nipy` for testing, transitively through the `nipype.algorithms.metrics.Similairy`. `nipy` fails to install on Python 3.10 with Poetry 1.2, forcing us to pin the minimum version of Poetry to 1.1.x for the moment. I forwarded the issue upstream and got an immediate reply.

Poetry advised to forward the issue to `nipy` and advise them to transition their build system to something [PEP-518](https://peps.python.org/pep-0518) compliant. Unlike standard `setup.py` scripts however, nipy's make heavy use of `numpy.distutils` specific features (which is deprecated since version 1.23 and is planned for removal in Python 3.12) which are pretty complex, if not impossible to transition to plain `setuptools`. It is similar in its structure to what the build system used to look like in `scipy`, which chose to transition to `meson` instead. I don't think `nipy` will have the manpower nor the will to operate such transition any time soon.

In my opinion, the path to least resistance sounds to just vendor or implement our own similarity function and just drop the burden of depending on `nipy`. We hardly use anything in it, yet this dependency is going to become an annoyance for supporting future versions of Python.

**Comment by ghisvail** [comment]
Useful references:

- Bug report in [Poetry](https://github.com/python-poetry/poetry/issues/6279)

- `numpy.distutils` [deprecation](https://numpy.org/devdocs/reference/distutils_status_migration.html)

**Comment by ghisvail** [comment]
[Request](https://github.com/nipy/nipy/issues/494) for a refresh of wheels for `nipy`

**Comment by omar-rifai** [comment]
Great, thanks for following up. I think looking for an alternative to the similarity function is indeed the path we should look into.

**Comment by ghisvail** [comment]
Confirmed by Chris. The project is unmaintained, so vendoring or providing our own implementation looks inevitable.
