### ISSUE TITLE
'Clinica run t1-linear' crashes under Linux but works under MacOS

### ISSUE THREAD

**Issue by Armen-G-G** [aramis-lab/clinica#735]
Hi,

I'm trying to use ClinicaDL over the OASIS-1 data. After `clinica covert oasis-to-bids` I try to preprocessing images by running `clinica run t1-linear`. But this command crushes under Linux (tested on Ubuntu 22.04 and on Linux Mint 21). The same command on the same data works well under the MacOS Big Sur.

Here is the crash log from Linux Mint 21:
> (clinicadlEnv) alzheimer@alzheimer-desktop:~/MRI$ clinica run t1-linear BIDS_Linux/ CAPS_Linux/
> 
> 2022-09-05 09:54:57,480:INFO:The pipeline will be run on the following 235 image(s):
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10001 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10002 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10003 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10010 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10011 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10013 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10015 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10016 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10018 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10019 | ses-M00,
> 2022-09-05 09:54:57,480:INFO:	sub-OASIS10020 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10021 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10022 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10023 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10026 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10028 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10030 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10031 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10032 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10033 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10034 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10035 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10039 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10041 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10042 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:	...
> 2022-09-05 09:54:57,481:INFO:	sub-OASIS10457 | ses-M00,
> 2022-09-05 09:54:57,481:INFO:The pipeline will last approximately 6 minutes per image.
> 2022-09-05 09:54:58,767:WARNING:You did not specify the number of threads to run in parallel (--n_procs argument).
> 2022-09-05 09:54:58,767:WARNING:Computation time can be shorten as you have 8 CPUs on this computer. We recommend using 7 threads.
> How many threads do you want to use? [7]: 
> Number of threads set to 7. You may set the --n_procs argument to disable this message for future calls.
> Traceback (most recent call last):
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/bin/clinica", line 8, in <module>
>     sys.exit(main())
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/clinica/cmdline.py", line 89, in main
>     cli()
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/clinica/pipelines/t1_linear/t1_linear_cli.py", line 58, in cli
>     else pipeline.run()
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/clinica/pipelines/engine.py", line 288, in run
>     raise e
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/clinica/pipelines/engine.py", line 269, in run
>     exec_graph = Workflow.run(self, plugin, plugin_args, update_hash)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 166, in run
>     self._clean_queue(jobid, graph, result=result)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 244, in _clean_queue
>     raise RuntimeError("".join(result["traceback"]))
> RuntimeError: Traceback (most recent call last):
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node n4biascorrection.
> 
> Traceback (most recent call last):
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
>     setattr(outputs, key, val)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
>     value = super(File, self).validate(objekt, name, value, return_pathlike=True)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
>     self.error(objekt, name, str(value))
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
>     raise TraitError(
> traits.trait_errors.TraitError: The 'bias_image' trait of a N4BiasFieldCorrectionOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/tmp/tmp28xc6ki4/t1-linear/311d3cd145868a4a29729da8fce6805c1f2ed561/n4biascorrection/sub-OASIS10013_ses-M00_T1w_bias.nii.gz' <class 'str'> was specified.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
>     outputs = self.aggregate_outputs(runtime)
>   File "/home/alzheimer/miniconda3/envs/clinicadlEnv/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
>     raise FileNotFoundError(msg)
> FileNotFoundError: No such file or directory '/tmp/tmp28xc6ki4/t1-linear/311d3cd145868a4a29729da8fce6805c1f2ed561/n4biascorrection/sub-OASIS10013_ses-M00_T1w_bias.nii.gz' for output 'bias_image' of a N4BiasFieldCorrection interface
> 
> (clinicadlEnv) alzheimer@alzheimer-desktop:~/MRI$

**Comment by omar-rifai** [comment]
Hello @Armen-G-G, 

Thanks for your interest in Clinica/ClinicaDL. 

It looks like the error is related to the `Ants` command for biascorrection. Can you please confirm that:

(1) You are on the latest version of Clinica (currently v.0.7.2)
(2) Ants is installed and functional on your system
(3) You can run the ants command `N4BIASFIELDCORRECTION` on a file outside of clinica

Thanks, 

Omar

**Comment by Armen-G-G** [comment]
Hello Omar,

Thanks for you answer!

> (1) You are on the latest version of Clinica (currently v.0.7.2) 

Yes, `clinica --version` shows `clinica, version 0.7.2`

> (2) Ants is installed and functional on your system 

Yes, ANTs is installed and fuctional

> (3) You can run the ants command `N4BIASFIELDCORRECTION` on a file outside of clinica

I have tested it by running
`N4BiasFieldCorrection -i ./BIDS_MAC/sub-OASIS10001/ses-M00/anat/sub-OASIS10001_ses-M00_T1w.nii.gz  -o sub-OASIS1001_ses-M00_T1w.nii.gz`
After few minutes I have found the `sub-OASIS1001_ses-M00_T1w.nii.gz` file in the folder. Seems to be correct file. There were no error or warning messages.

Armen

**Comment by omar-rifai** [comment]
Ok perfect. Can you please run the command specifying the argument:

--working_directory <directory>

Once the pipeline crashes, you'll be able to find inside the directory the directory for 'N4BiasFieldCorrection' along with a `command.txt` file with the command that crashed. 

Can try running the command manually to have a more informative error message and paste it here?

Thank you

**Comment by Armen-G-G** [comment]
Following is a output of a `tree` command in the `temp_dir/t1-linear` folder (I shortened the tree a bit and left only the contents of the `n4biascorrection` folders):

├── 2c7b5ecfdb4973ac595ca093a25ce0d10be8f785
│└── n4biascorrection
│       ├── command.txt
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       └── result_n4biascorrection.pklz
├── 2ddf6e8c99bfcc1cd107457679d7790095aa6a8c
│└── n4biascorrection
│       ├── command.txt
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       └── result_n4biascorrection.pklz
├── 311d3cd145868a4a29729da8fce6805c1f2ed561
│└── n4biascorrection
│       ├── _0x41fd8483f1569defcbdd29e5e9a64d15.json
│       ├── command.txt
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       ├── result_n4biascorrection.pklz
│       ├── **sub-OASIS10013_ses-M00_T1w_bias.nii.gz**
│       └── **sub-OASIS10013_ses-M00_T1w_corrected.nii.gz**
├── 349ca9d6758dbf3944bc7e8dc194c8c58f92630c
│└── n4biascorrection
│       ├── command.txt
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       └── result_n4biascorrection.pklz
├── 44b81f9d151deb606d7d4501b018ec5c1b3c11d6
│└── n4biascorrection
│       ├── _0x704fb13e67e813caeaa6fa324f003044.json
│       ├── command.txt
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       ├── result_n4biascorrection.pklz
│       ├── **sub-OASIS10001_ses-M00_T1w_bias.nii.gz**
│       └── **sub-OASIS10001_ses-M00_T1w_corrected.nii.gz**
├── 95eb8cbe651612eb73a08ea5faf8ed8a2608bfc3
│└── n4biascorrection
│       ├── command.txt
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       └── result_n4biascorrection.pklz
├── 9e660cfffa1648ca2d7f55100d6345377aa295a0
│└── n4biascorrection
│       ├── _0xbc10eabd31f5c04c44dfbf45dcf04dac.json
│       ├── command.txt
│       ├── _inputs.pklz
│       ├── _node.pklz
│       ├── _report
│       │   └── report.rst
│       ├── result_n4biascorrection.pklz
│       ├── **sub-OASIS10003_ses-M00_T1w_bias.nii.gz**
│       └── **sub-OASIS10003_ses-M00_T1w_corrected.nii.gz**
├── d3.js
├── graph1.json
├── graph.json
└── index.html

Here is content of a `command.txt` file in one of the folder:
`N4BiasFieldCorrection --bspline-fitting [ 600 ] -d 3 --input-image /home/alzheimer/MRI/BIDS_Linux/sub-OASIS10011/ses-M00/anat/sub-OASIS10011_ses-M00_T1w.nii.gz --output [ sub-OASIS10011_ses-M00_T1w_corrected.nii.gz, sub-OASIS10011_ses-M00_T1w_bias.nii.gz ]`

You can see that some folder does contain `nii.gz` files (marked bold), some does not.

**Comment by omar-rifai** [comment]
if it is still processing, it is normal that some contain the `nii.gz`and other not. If it crashes, you can try to run the command inside "command.txt" manually for the subject/session that crashed. (e.g sub-OASIS10013_ses-M00_) in your first message.

**Comment by Armen-G-G** [comment]
It seems that this is a problem with insufficient memory (or other system resource).
I tried to reduce number of threads for the t1-linear task from 7 to 5 - crashed again.
Then I reduced threads count to 4 – pipeline still running, 36 subjects processed already. Hope all tasks will be finished correctly.
I will write an additional comment when the whole task is completed and will close this issue.

**Comment by Armen-G-G** [comment]
Hi Omar,

Now I can confirm that the problem was in insufficient computer resources (I guest the 16 GB RAM whas not enough). 
Whith number of processes (--n_procs) equal to 4 all convertations were completed this night.
So, I'm clossing this issue.

Thank you a lot for your help!
