### ISSUE TITLE
Why are MB fMRI scans ignored (adni-to-bids)?

### ISSUE THREAD

**Issue by ConnorBehnen** [aramis-lab/clinica#740]
**Description**
Per the [adni-to-bids documentation](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/), multiband fMRI images are ignored. While I understand there might be some differences that need to be accounted for in analysis, I'm wondering why they shouldn't be included in BIDS conversion? Based on my experience, ADNI3 contains a not insignificant number of MB scans. In fact, the only reason I discovered MB images weren't being converted was because many of my subjects have _only_ had MB scans even over multiple years of sessions (examples: 007_S_6255, 023_S_6661).

For reference, [this comment](https://neurostars.org/t/fmri-multiband-preprocessing/6598/2) by Chris Rorden is the best description of multiband fMRI that I've seen.

**Comment by ghisvail** [comment]
> Per the [adni-to-bids documentation](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/), multiband fMRI images are ignored.

We (The Aramis Lab) don't have much use cases for them at the moment.

> I'm wondering why they shouldn't be included in BIDS conversion?

Feel free to have a go at it 👍

**Comment by vnckppl** [comment]
I was also interested in including the multiband images. I only use clinica for ADNI to BIDS conversion. If that is your goal too, you can comment out the following lines in [this](https://github.com/aramis-lab/clinica/blob/04a44994e8f14ba0474314719d1ee35fad3c51d1/clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmri.py) script to have multiband images converted to BIDS:

```
    unwanted_sequences = ["MB"]
    mri_list = mri_list[
        mri_list.SEQUENCE.map(
            lambda x: not any(subs in x for subs in unwanted_sequences)
        )
    ]
```

I assume this will be highly similar if not identical for other data collections that clinica has a BIDS conversion method for.

**Comment by NicolasGensollen** [comment]
Re-opening this as we might implement an option to enable conversion of multiband scans in the ADNI converter.
