### ISSUE TITLE
Consider removing unused function `have_same_subjects`

### ISSUE THREAD

**Issue by NicolasGensollen** [aramis-lab/clinica#750]
The function `have_same_subjects`, defined here:

https://github.com/aramis-lab/clinica/blob/480532bff68da9428c8125a2f6b9f808d9ea6862/clinica/utils/participant.py#L135-L136

seems to be only used here in a commented line:

https://github.com/aramis-lab/clinica/blob/e722723ef5f7dcc213436d099ccd90605e3aeba3/clinica/pipelines/statistics_surface/statistics_surface_pipeline.py#L121

Should we remove it ?

**Comment by ghisvail** [comment]
I am in favour of removing dead code.

Besides, the function name is misleading since it checks subject session pairs, not just subjects, and the implementation is not idiomatic Pandas code.
