### ISSUE TITLE
Logging breaks when launched from a directory with no write privileges

### ISSUE THREAD

**Issue by danieltudosiu** [aramis-lab/clinica#771]
**Describe the bug**
Given an adequately configured GPU cluster where you can't run as root in a Docker container neither can you write on at the following location "/" clinica adni-to-bids breaks due to permission issues.

**To Reproduce**

Dockerfile:
```
FROM continuumio/miniconda3

ARG USER_ID
ARG GROUP_ID
ARG USER
RUN addgroup --gid $GROUP_ID $USER
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID $USER


RUN apt-get update && apt-get install -y build-essential

RUN conda install python==3.9
RUN conda install -c conda-forge dcm2niix
RUN pip install clinica==0.7.2
```
Run script
```

runai submit clinica-adni-to-bids \
  --image 10.202.67.207:5000/danieltudosiu:clinica_0_7_2 \
  --volume /nfs/project/AMIGO/ADNI_MRI/metadata/:/clinica_data_directory/ \
  --volume /nfs/project/AMIGO/ADNI_MRI/sourcedata/ADNI/:/dataset_directory/ \
  --volume /nfs/project/AMIGO/ADNI_MRI/rawdata/:/bids_directory/ \
  --large-shm \
  --host-network \
  --backoff-limit 0 \
  --gpu 0 \
  --cpu 8 \
  --project danieltudosiu \
  --command \
  -- clinica convert adni-to-bids --working_directory /bids_directory --n_procs 16 /dataset_directory /clinica_data_directory /bids_directory
```

Just run it in a Docker container as a non-root user and you should have the same issue.

**Expected behavior**
Be allowed to select the logging directory.

**Comment by NicolasGensollen** [comment]
Hi @danieltudosiu 

Thanks for reporting. Could you also share the error you get? By reading your message, it is not obvious that it is related to log file writing permissions.

**Comment by danieltudosiu** [comment]
@ghisvail  @NicolasGensollen  the reason that I pushed the change directly to the logger that is given the Python is because that's the logger that errors out for me by giving the following trace:
```
Traceback (most recent call last):
  File "/opt/conda/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/clinica/cmdline.py", line 89, in main
    cli()
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/clinica/cmdline.py", line 78, in cli
    setup_logging(verbose=verbose)
  File "/opt/conda/lib/python3.9/site-packages/clinica/cmdline.py", line 67, in setup_logging
    nipype.logging.update_logging(nipype.config)
  File "/opt/conda/lib/python3.9/site-packages/nipype/utils/logger.py", line 88, in update_logging
    self.enable_file_logging()
  File "/opt/conda/lib/python3.9/site-packages/nipype/utils/logger.py", line 54, in enable_file_logging
    hdlr = RFHandler(
  File "/opt/conda/lib/python3.9/logging/handlers.py", line 153, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/opt/conda/lib/python3.9/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/opt/conda/lib/python3.9/logging/__init__.py", line 1142, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/conda/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/pypeline.log'

```
If you can advise where the change should be made I will give it a go today.

**Comment by ghisvail** [comment]
Ok so it looks like `nipype` eagerly generates the log file even if it's not used.

Then my [comment](https://github.com/aramis-lab/clinica/pull/772#discussion_r999129930) still stands. It should be enough to provide a way to override the value of `log_directory`.

I suspect the reason the log file gets written in `/pypeline.log` is that that `WORKDIR` is set to `/` by default in Docker, so the comment gets executed with `/` as its cwd. Setting `WORKDIR` to somewhere else which is writeable like `/tmp` or `/home/some_user` should not yield a permission error.

**Comment by danieltudosiu** [comment]
I think you already have that as the -wd --working_directory flag but it does not have an effect on the nypipe logging. Should we then use it as well, this would reduce the number of flags as well as be coherent.

**Comment by ghisvail** [comment]
I actually believe your issue is not specific to Docker, and the same behaviour would happen if you ran Clinica from `/` as a normal user. If that's confirmed, perhaps this issue could be renamed as `Logging breaks when launched from a directory with no write priviledge`

**Comment by danieltudosiu** [comment]
@ghisvail I think it is already confirmed as per @NicolasGensollen [comment](https://github.com/aramis-lab/clinica/pull/772#pullrequestreview-1146954503). 

I will go forward and work on getting the -wd used to overwrite nipype's logging directory.

**Comment by danieltudosiu** [comment]
I tried to give it a go as per my last pull request #772 but I am not familiar with the click package.

I tried to add the -wd argument found [here](https://github.com/aramis-lab/clinica/blob/e722723ef5f7dcc213436d099ccd90605e3aeba3/clinica/engine/cmdparser.py#L108) and use it similarly to [here ](https://github.com/aramis-lab/clinica/blob/7558227700366fa499a686409385869e2fd00292/clinica/pipelines/t1_volume/t1_volume_cli.py#L18) but it seems I am doing it wrongly.

Could you please advise?

**Comment by ghisvail** [comment]
On second thoughts, I am convinced working directories and logging should be separate concerns. The former contains the transient artefacts generated whilst running the pipeline and is utltimately cleaned on success. On the other hand, logs are operational information and should be kept at all time, even on successful completion of a pipeline.

Now moving forward, here's what I'd propose:

1. Extend `setup_logging` to allow a `logging_dir` parameter initialised to `os.getcwd` to keep backward compatibility. Since `os.getcwd` is a side effect, it's better to call it from within the function instead of as a default parameter.

2. Introduce a `CLINICA_LOGGING_DIR` environment variable which will allow you to setup Docker to write logging results to the specific volume you want.

Overall it would look like this:

```
def setup_logging(..., logging_dir: os.PathLike = None):
    from pathlib import PurePath

    ...

    logging_dir = logging_dir or PurePath(os.getenv("CLINICA_LOGGING_DIR", os.getcwd()))

    ...

    nipype.config.update_config(
        {
            "logging": {
                "log_directory": os.fspath(logging_dir),
                ...
            }
         ...
         }

     ...
```

**Comment by ghisvail** [comment]
I still wonder whether adding a `WORKDIR /home/clinica` at the end of your Docker recipe would have worked. Relying on the default `WORKDIR` set by your base image is a known Docker smell.

**Comment by danieltudosiu** [comment]
@ghisvail will give a go to the WORKDIR fix that you mentioned and will get back to you. Meanwhile, do you want me to still pursue the suggested fix for clinica?

**Comment by ghisvail** [comment]
> @ghisvail will give a go to the WORKDIR fix that you mentioned and will get back to you. Meanwhile, do you want me to still pursue the suggested fix for clinica?

Of course, feel free to apply my suggestion to your current PR 👍 

You've pointed an important weakness of Clinica that did not show up in local workflows, but definitely needs fixing for containerised runs.
