### ISSUE TITLE
FWHM seems unused in statistics-volume pipeline with t1-volume data

### ISSUE THREAD

**Issue by AudreyDuran** [aramis-lab/clinica#830]
In statistics-volume pipeline, [FWHM can be set and is 8 by default](https://github.com/aramis-lab/clinica/blob/02aaa90321ec853fb09ea2f965b1b338921a1845/clinica/pipelines/statistics_volume/statistics_volume_cli.py#L28).

But during data loading, if `t1-volume` is used as `orig_input_data_volume`, then `t1_volume_template_tpm_in_mni` is [called](https://github.com/aramis-lab/clinica/blob/02aaa90321ec853fb09ea2f965b1b338921a1845/clinica/pipelines/statistics_volume/statistics_volume_pipeline.py#L119), that loads [non smoothed data](https://github.com/aramis-lab/clinica/blob/02aaa90321ec853fb09ea2f965b1b338921a1845/clinica/utils/input_files.py#L417).

This is different from `pet-volume` pipeline where the `fwhm` is used to define the [`information_dict`](https://github.com/aramis-lab/clinica/blob/02aaa90321ec853fb09ea2f965b1b338921a1845/clinica/pipelines/statistics_volume/statistics_volume_pipeline.py#L115).

In the output files though, `fwhm` is set to 8 while it seems that the volumes used to compute the statistics were not smoothed.

Am I missing something here ?

**Comment by NicolasGensollen** [comment]
Thanks for reporting @AudreyDuran. I had a quick look and I believe you are right. When specifying fwhm in the command line of statistics volume, the value should be used for reading both pet volume and t1 volume obtained images.

It seems like we should modify this function:

https://github.com/aramis-lab/clinica/blob/02aaa90321ec853fb09ea2f965b1b338921a1845/clinica/utils/input_files.py#L404-L424

to accept a new `fwhm` argument and make the proper path matching.
This function is also used in the t1 volume parcellation pipeline:

https://github.com/aramis-lab/clinica/blob/47f22c051ff019de28b0559b5f2d9e52ce3c9000/clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_pipeline.py#L73-L77

which, similarly, seems to not consider `fwhm` at all...
