### ISSUE TITLE
Wrong phase mapping in `generate_acq_file`

### ISSUE THREAD

**Issue by NicolasGensollen** [aramis-lab/clinica#887]
See: 

https://github.com/aramis-lab/clinica/blob/98c8b8c5a9350f37e2c6247914a6d6aacc919801/clinica/utils/dwi.py#L343

Unless I missed something, it should be (0, 0, 1, ...), right ?

**Comment by alexandreroutier** [comment]
Hi Nicolas,

I'm afraid you are right, this should be 0, 0, 1 in z-axis, I don't know when the bug was added in Clinica, probably when the DWI pipelines were updated.

**Comment by NicolasGensollen** [comment]
Hi @alexandreroutier 
Thanks for your fast reply ! 👍 
Yes, the bug seem pretty ancient and I believe it has already impacted the data we use for testing the DWI pipelines.

**Comment by NicolasGensollen** [comment]
In #888 and #889 I'm refactoring and testing functions `generate_acq_file` and `generate_index_file` which are used together in order to give two input files to `Eddy`:

- the acquisition file which specifies how the phase-encoding is performed, it basically looks like this:

```
-1 0 0 0.051
1 0 0 0.051
```

- the index file which specifies how each volume was acquired. It is basically a list of integers encoding the relationship between the volume index and the row index of the acquisition file. For example:

```
1 1 1 1 2 2 2 2
```

means that  the first four volumes were acquired using the acquisition parameters on the first row (index 1), and that volumes 5--8 were acquired according to the second row (index 2).

The rows in the acquisition file are built using the following code:

https://github.com/aramis-lab/clinica/blob/6e98d8a29434dfae1afa909f5215731638dbcd8a/clinica/utils/dwi.py#L333-L345

which basically writes the same line `nb_volumes` times because the `fsl_phase_encoding_direction` is a constant string in this loop.

I might be missing something, but if this behavior is correct, I don't understand why we need to write all these lines if they are the same. If I understand the Eddy documentation well, we could achieve the exact same behavior by just writing a single line in the acquisition file, and setting all indices in the index file as ones.

Furthermore, the following code performs the construction of the index file content:

https://github.com/aramis-lab/clinica/blob/6e98d8a29434dfae1afa909f5215731638dbcd8a/clinica/utils/dwi.py#L289-L301

I must admit that I don't understand what is the purpose of this loop. It seems like B0 volumes should get a different acquisition row index as the other volumes, but:

- as explained above, all rows are the same
- I suspect you can easily end up having non-matching lengths between the `index_list` and the `vols` lists.

My super naïve unit test in #889 for example ends up in this situation:

```python
# DWI data is 8 volumes
# B0 volumes are at indices 2, 3, 4, and 7
np.savetxt(tmp_path / "foo.bval", [1000, 1000, 0, 0, 0, 1000, 1000, 0])
index_file = generate_index_file(str(tmp_path / "foo.bval"))
```

The computed index list is `[1, 2, 3, 3, 3, 4]`, which is length 6 instead of 8...

Is there some implicit constraints for B0 volumes that this test is breaking?

Does this make sense ? @alexandreroutier ? @ghisvail ? @MatthieuJoulot
