### ISSUE TITLE
Replace `get_data()` by `get_fdata()` method for dataobj_images (nibabel)

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinica#89]
The `get_data()` method from _dataobj_images_  class will be deprecated (Nov 2019) and removed from Nibabel (Nov 2021). All occurrences should be updates before these dates. See [official doc](https://nipy.org/nibabel/reference/nibabel.dataobj_images.html).

**Comment by omar-rifai** [comment]
Fixed in PR#[291](https://github.com/aramis-lab/clinica/pull/291)
