### ISSUE TITLE
Scikit-Image 0.17.X not working when installing Clinica

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#93]
See PR #92 for details.

For the moment, we will fix to the `0.16.2` version (latest 0.16.X version) since the dev are releasing quite frequently new versions of 0.17.X (https://github.com/scikit-image/scikit-image/releases).

To investigate when the 0.17.X will be stabilised.

**Comment by mdiazmel** [comment]
Solved (temporary). Scikit-image version is frozen by commit 541df283.
