### ISSUE TITLE
OASIS3 to BIDS not working well with me

### ISSUE THREAD

**Issue by YasmineMH1997** [aramis-lab/clinica#941]
Introduction of the discussion topic.
<img width="692" alt="image" src="https://github.com/aramis-lab/clinica/assets/128826190/2bbc1a8f-e45d-46f5-9c64-72bd3479a3cb">
I am trying to convert OASIS 3 to BIDS
But for example Tw1 files are only a few kb of size. Thus data are not properly converted. 
<img width="262" alt="image" src="https://github.com/aramis-lab/clinica/assets/128826190/d5e8dc6b-b996-4f69-90b6-af856a4f4821">

Consequently, whenever I apply the fmriprep-docker command I get the  following errors: 

`fmriprep-docker C:\Users\yasmi\Desktop\Oasis\BIDS C:\Users\yasmi\Desktop\Oasis\BIDS\derivatives --fs-license-file C:/Users/yasmi/Desktop/Oasis/license.txt  --skip-bids-validation --anat-only`

`   fmriprep_23_0_wf.single_subject_OAS31147_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions
230609-11:30:30,710 nipype.workflow ERROR:
         could not run node: fmriprep_23_0_wf.single_subject_OAS31148_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions
230609-11:30:30,714 nipype.workflow ERROR:
         could not run node: fmriprep_23_0_wf.single_subject_OAS31149_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions
230609-11:30:30,719 nipype.workflow ERROR:
         could not run node: fmriprep_23_0_wf.single_subject_OAS31150_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions
230609-11:30:30,723 nipype.workflow ERROR:
         could not run node: fmriprep_23_0_wf.single_subject_OAS31151_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions
230609-11:30:30,728 nipype.workflow ERROR:
         could not run node: fmriprep_23_0_wf.single_subject_OAS31152_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions
230609-11:30:30,733 nipype.workflow ERROR:
         could not run node: fmriprep_23_0_wf.single_subject_OAS31153_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions
230609-11:30:30,737 nipype.workflow ERROR:
         could not run node: fmriprep_23_0_wf.single_subject_OAS31154_wf.anat_preproc_wf.anat_template_wf.anat_ref_dimensions`

+---sub-OAS30518
|   |   sub-OAS30518_sessions.tsv
|   |
|   \---ses-M000
|       \---anat
|               sub-OAS30518_ses-M000_T1w.nii.gz
|
+---sub-OAS30519
|   |   sub-OAS30519_sessions.tsv
|   |
|   \---ses-M000
|       +---anat
|       |       sub-OAS30519_ses-M000_T1w.nii.gz
|       |
|       \---pet
|               sub-OAS30519_ses-M000_trc-18FAV45_pet.nii.gz
|
+---sub-OAS30521
|   |   sub-OAS30521_sessions.tsv
|   |
|   +---ses-M006
|   |   \---anat
|   |           sub-OAS30521_ses-M006_T1w.nii.gz
|   |
|   \---ses-M030
|       \---anat
|               sub-OAS30521_ses-M030_T1w.nii.gz
|
+---sub-OAS30522
|   |   sub-OAS30522_sessions.tsv
|   |
|   \---ses-M006
|       +---anat
|       |       sub-OAS30522_ses-M006_T1w.nii.gz
|       |
|       \---pet
|               sub-OAS30522_ses-M006_trc-18FAV45_pet.nii.gz
|
+---sub-OAS30523
|   |   sub-OAS30523_sessions.tsv
|   |
|   \---ses-M000
|       \---anat
|               sub-OAS30523_ses-M000_T1w.nii.gz

**Comment by NicolasGensollen** [comment]
Hi @YasmineMH1997 

Thanks for reporting. Could you specify the version of Clinica you are using ?
Version `0.7.5` was released a few days ago with some bug fixes for converters.

**Comment by ghisvail** [comment]
@YasmineMH1997, could you try displaying the T1w files with a viewer such as [niivue](https://github.com/niivue/niivue) or [medInria](https://med.inria.fr/) ? Just to check the converted files are sound before attempting to preprocess them with another tool.

I notice you're running your processing on Windows, which we do not officially test for nor support.

**Comment by YasmineMH1997** [comment]
> @YasmineMH1997, could you try displaying the T1w files with a viewer such as [niivue](https://github.com/niivue/niivue) or [medInria](https://med.inria.fr/) ? Just to check the converted files are sound before attempting to preprocess them with another tool.
> 
> I notice you're running your processing on Windows, which we do not officially test for nor support.

Thank you so much for your response. I used 
`pip install clinica`
this should install the latest version, right?
The viewer didn't show anything, unfortunately. 
Do you suggest I install a linux virtual box? 
Also is the format of the installed OASIS 3 correct?
+---OAS31437_PIB_d0115
|   \---pet1
|           sub-OAS31437_ses-d0115_acq-PIB_run-02_pet.json
|           sub-OAS31437_ses-d0115_acq-PIB_run-02_pet.nii.gz
|           sub-OAS31437_ses-d0115_acq-PIB_run-02_pet.tsv
|
+---OAS31439_MR_d0081
|   \---anat2
|           sub-OAS31439_sess-d0081_T1w.json
|           sub-OAS31439_sess-d0081_T1w.nii.gz
|
+---OAS31439_PIB_d0081
|   \---pet1
|           sub-OAS31439_ses-d0081_acq-PIB_pet.json
|           sub-OAS31439_ses-d0081_acq-PIB_pet.nii.gz
|           sub-OAS31439_ses-d0081_acq-PIB_pet.tsv
|
+---OAS31440_MR_d0040
|   \---anat2
|           sub-OAS31440_sess-d0040_T1w.json
|           sub-OAS31440_sess-d0040_T1w.nii.gz
|
+---OAS31440_PIB_d0040
|   \---pet1
|           sub-OAS31440_ses-d0040_acq-PIB_run-03_pet.json
|           sub-OAS31440_ses-d0040_acq-PIB_run-03_pet.nii.gz
|           sub-OAS31440_ses-d0040_acq-PIB_run-03_pet.tsv
|
+---OAS31441_AV45_d0067
|   \---pet1
|           sub-OAS31441_ses-d0067_acq-AV45_run-08_pet.json
|           sub-OAS31441_ses-d0067_acq-AV45_run-08_pet.nii.gz
|           sub-OAS31441_ses-d0067_acq-AV45_run-08_pet.tsv
|
+---OAS31441_MR_d0067
|   \---anat4
|           sub-OAS31441_sess-d0067_T1w.json
|           sub-OAS31441_sess-d0067_T1w.nii.gz
|
+---OAS31442_AV45_d0084
|   \---pet1
|           sub-OAS31442_ses-d0084_acq-AV45_run-02_pet.json
|           sub-OAS31442_ses-d0084_acq-AV45_run-02_pet.nii.gz
|           sub-OAS31442_ses-d0084_acq-AV45_run-02_pet.tsv
|
+---OAS31442_MR_d0084
|   \---anat4
|           sub-OAS31442_sess-d0084_T1w.json
|           sub-OAS31442_sess-d0084_T1w.nii.gz
|
+---OAS31444_AV45_d0321
|   \---pet1
|           sub-OAS31444_ses-d0321_acq-AV45_run-09_pet.json
|           sub-OAS31444_ses-d0321_acq-AV45_run-09_pet.nii.gz
|           sub-OAS31444_ses-d0321_acq-AV45_run-09_pet.tsv
|
+---OAS31444_MR_d0321
|   \---anat2
|           sub-OAS31444_sess-d0321_T1w.json
|           sub-OAS31444_sess-d0321_T1w.nii.gz
|
+---OAS31446_MR_d0070
|   \---anat4
|           sub-OAS31446_sess-d0070_T1w.json
|           sub-OAS31446_sess-d0070_T1w.nii.gz
|
+---OAS31446_PIB_d0070
|   \---pet1
|           sub-OAS31446_ses-d0070_acq-PIB_run-03_pet.json
|           sub-OAS31446_ses-d0070_acq-PIB_run-03_pet.nii.gz
|           sub-OAS31446_ses-d0070_acq-PIB_run-03_pet.tsv
|
+---OAS31447_AV45_d0089
|   \---pet1
|           sub-OAS31447_ses-d0089_acq-AV45_run-04_pet.json
|           sub-OAS31447_ses-d0089_acq-AV45_run-04_pet.nii.gz
|           sub-OAS31447_ses-d0089_acq-AV45_run-04_pet.tsv
|
+---OAS31447_MR_d0089
|   \---anat4
|           sub-OAS31447_sess-d0089_T1w.json
|           sub-OAS31447_sess-d0089_T1w.nii.gz
|
+---OAS31448_MR_d0137
|   \---anat2
|           sub-OAS31448_sess-d0137_T1w.json
|           sub-OAS31448_sess-d0137_T1w.nii.gz
|
+---OAS31448_PIB_d0137
|   \---pet1
|           sub-OAS31448_ses-d0137_acq-PIB_pet.json
|           sub-OAS31448_ses-d0137_acq-PIB_pet.nii.gz
|           sub-OAS31448_ses-d0137_acq-PIB_pet.tsv
|
+---OAS31449_MR_d0063
|   \---anat2
|           sub-OAS31449_sess-d0063_T1w.json
|           sub-OAS31449_sess-d0063_T1w.nii.gz
|
+---OAS31449_PIB_d0063
|   \---pet1
|           sub-OAS31449_ses-d0063_acq-PIB_run-03_pet.json
|           sub-OAS31449_ses-d0063_acq-PIB_run-03_pet.nii.gz
|           sub-OAS31449_ses-d0063_acq-PIB_run-03_pet.tsv
|
+---OAS31450_AV45_d0379
|   \---pet1
|           sub-OAS31450_ses-d0379_acq-AV45_run-04_pet.json
|           sub-OAS31450_ses-d0379_acq-AV45_run-04_pet.nii.gz
|           sub-OAS31450_ses-d0379_acq-AV45_run-04_pet.tsv
|
+---OAS31450_MR_d0379
|   \---anat4
|           sub-OAS31450_sess-d0379_T1w.json
|           sub-OAS31450_sess-d0379_T1w.nii.gz
|
+---OAS31453_AV45_d0197
|   \---pet1
|           sub-OAS31453_ses-d0197_acq-AV45_run-02_pet.json
|           sub-OAS31453_ses-d0197_acq-AV45_run-02_pet.nii.gz
|           sub-OAS31453_ses-d0197_acq-AV45_run-02_pet.tsv
|
+---OAS31453_MR_d0197
|   \---anat4
|           sub-OAS31453_sess-d0197_T1w.json
|           sub-OAS31453_sess-d0197_T1w.nii.gz
|
+---OAS31455_AV45_d0087
|   \---pet1
|           sub-OAS31455_ses-d0087_acq-AV45_run-06_pet.json
|           sub-OAS31455_ses-d0087_acq-AV45_run-06_pet.nii.gz
|           sub-OAS31455_ses-d0087_acq-AV45_run-06_pet.tsv
|
+---OAS31455_MR_d0087
|   \---anat2
|           sub-OAS31455_sess-d0087_T1w.json
|           sub-OAS31455_sess-d0087_T1w.nii.gz
|
+---OAS31456_AV45_d0090
|   \---pet1
|           sub-OAS31456_ses-d0090_acq-AV45_run-04_pet.json
|           sub-OAS31456_ses-d0090_acq-AV45_run-04_pet.nii.gz
|           sub-OAS31456_ses-d0090_acq-AV45_run-04_pet.tsv
|
+---OAS31456_MR_d0090
|   \---anat4
|           sub-OAS31456_sess-d0090_T1w.json
|           sub-OAS31456_sess-d0090_T1w.nii.gz
|
+---OAS31457_AV45_d0113
|   \---pet1
|           sub-OAS31457_ses-d0113_acq-AV45_run-04_pet.json
|           sub-OAS31457_ses-d0113_acq-AV45_run-04_pet.nii.gz
|           sub-OAS31457_ses-d0113_acq-AV45_run-04_pet.tsv
|
+---OAS31457_MR_d0113
|   \---anat2
|           sub-OAS31457_sess-d0113_T1w.json
|           sub-OAS31457_sess-d0113_T1w.nii.gz
|
+---OAS31457_MR_d0114
|   \---anat1
|           sub-OAS31457_sess-d0114_T1w.json
|           sub-OAS31457_sess-d0114_T1w.nii.gz
|
+---OAS31458_MR_d0030
|   \---anat2
|           sub-OAS31458_sess-d0030_T1w.json
|           sub-OAS31458_sess-d0030_T1w.nii.gz
|
+---OAS31458_PIB_d0030
|   \---pet1
|           sub-OAS31458_ses-d0030_acq-PIB_pet.json
|           sub-OAS31458_ses-d0030_acq-PIB_pet.nii.gz
|           sub-OAS31458_ses-d0030_acq-PIB_pet.tsv
|
+---OAS31459_AV45_d0125
|   \---pet1
|           sub-OAS31459_ses-d0125_acq-AV45_run-02_pet.json
|           sub-OAS31459_ses-d0125_acq-AV45_run-02_pet.nii.gz
|           sub-OAS31459_ses-d0125_acq-AV45_run-02_pet.tsv
|
+---OAS31459_MR_d0125
|   \---anat4
|           sub-OAS31459_sess-d0125_T1w.json
|           sub-OAS31459_sess-d0125_T1w.nii.gz
|
+---OAS31460_AV45_d0053
|   \---pet1
|           sub-OAS31460_ses-d0053_acq-AV45_run-04_pet.json
|           sub-OAS31460_ses-d0053_acq-AV45_run-04_pet.nii.gz
|           sub-OAS31460_ses-d0053_acq-AV45_run-04_pet.tsv
|
+---OAS31460_MR_d0053
|   \---anat4
|           sub-OAS31460_sess-d0053_T1w.json
|           sub-OAS31460_sess-d0053_T1w.nii.gz
|
+---OAS31462_MR_d0105
|   \---anat2
|           sub-OAS31462_sess-d0105_T1w.json
|           sub-OAS31462_sess-d0105_T1w.nii.gz
|
+---OAS31462_MR_d0107
|   \---anat4
|           sub-OAS31462_sess-d0107_T1w.json
|           sub-OAS31462_sess-d0107_T1w.nii.gz
|
+---OAS31463_MR_d0364
|   \---anat2
|           sub-OAS31463_sess-d0364_T1w.json
|           sub-OAS31463_sess-d0364_T1w.nii.gz
|
+---OAS31463_PIB_d0364
|   \---pet1
|           sub-OAS31463_ses-d0364_acq-PIB_pet.json
|           sub-OAS31463_ses-d0364_acq-PIB_pet.nii.gz
|           sub-OAS31463_ses-d0364_acq-PIB_pet.tsv
|
+---OAS31464_MR_d0014
|   \---anat2
|           sub-OAS31464_sess-d0014_T1w.json
|           sub-OAS31464_sess-d0014_T1w.nii.gz
|
+---OAS31464_PIB_d0014
|   \---pet1
|           sub-OAS31464_ses-d0014_acq-PIB_run-03_pet.json
|           sub-OAS31464_ses-d0014_acq-PIB_run-03_pet.nii.gz
|           sub-OAS31464_ses-d0014_acq-PIB_run-03_pet.tsv
|
+---OAS31465_AV45_d0089
|   \---pet1
|           sub-OAS31465_ses-d0089_acq-AV45_run-04_pet.json
|           sub-OAS31465_ses-d0089_acq-AV45_run-04_pet.nii.gz
|           sub-OAS31465_ses-d0089_acq-AV45_run-04_pet.tsv
|
+---OAS31465_MR_d0089
|   \---anat4
|           sub-OAS31465_sess-d0089_T1w.json
|           sub-OAS31465_sess-d0089_T1w.nii.gz
|
+---OAS31466_AV45_d0104
|   \---pet1
|           sub-OAS31466_ses-d0104_acq-AV45_run-02_pet.json
|           sub-OAS31466_ses-d0104_acq-AV45_run-02_pet.nii.gz
|           sub-OAS31466_ses-d0104_acq-AV45_run-02_pet.tsv
|
+---OAS31466_MR_d0104
|   \---anat2
|           sub-OAS31466_sess-d0104_T1w.json
|           sub-OAS31466_sess-d0104_T1w.nii.gz
|
+---OAS31469_AV45_d0105
|   \---pet1
|           sub-OAS31469_ses-d0105_acq-AV45_run-04_pet.json
|           sub-OAS31469_ses-d0105_acq-AV45_run-04_pet.nii.gz
|           sub-OAS31469_ses-d0105_acq-AV45_run-04_pet.tsv
|
+---OAS31469_MR_d0105
|   \---anat2
|           sub-OAS31469_sess-d0105_T1w.json
|           sub-OAS31469_sess-d0105_T1w.nii.gz
|
+---OAS31469_MR_d0106
|   \---anat1
|           sub-OAS31469_sess-d0106_T1w.json
|           sub-OAS31469_sess-d0106_T1w.nii.gz
|
+---OAS31470_MR_d0007
|   \---anat2
|           sub-OAS31470_sess-d0007_T1w.json
|           sub-OAS31470_sess-d0007_T1w.nii.gz
|
+---OAS31471_MR_d0059
|   \---anat2
|           sub-OAS31471_sess-d0059_T1w.json
|           sub-OAS31471_sess-d0059_T1w.nii.gz
|
+---OAS31471_PIB_d0059
|   \---pet1
|           sub-OAS31471_ses-d0059_acq-PIB_pet.json
|           sub-OAS31471_ses-d0059_acq-PIB_pet.nii.gz
|           sub-OAS31471_ses-d0059_acq-PIB_pet.tsv
|
+---OAS31472_MR_d0045
|   \---anat2
|           sub-OAS31472_sess-d0045_T1w.json
|           sub-OAS31472_sess-d0045_T1w.nii.gz
|
+---OAS31472_PIB_d0045
|   \---pet1
|           sub-OAS31472_ses-d0045_acq-PIB_run-03_pet.json
|           sub-OAS31472_ses-d0045_acq-PIB_run-03_pet.nii.gz
|           sub-OAS31472_ses-d0045_acq-PIB_run-03_pet.tsv
|
+---OAS31473_MR_d0136
|   \---anat2
|           sub-OAS31473_sess-d0136_T1w.json
|           sub-OAS31473_sess-d0136_T1w.nii.gz
|
\---OAS31474_MR_d0150
    \---anat2
            sub-OAS31474_sess-d0150_T1w.json
            sub-OAS31474_sess-d0150_T1w.nii.gz

**Comment by ghisvail** [comment]
>  The viewer didn't show anything, unfortunately.

Then, I am not surprised the rest of your preprocessing is failing. The issue stands definitely within the source data and / or the converter.

>  Also is the format of the installed OASIS 3 correct?

Mine differs slightly from yours.

```
├── OAS30010_AV45_d0068
│   ├── BIDS
│   │   └── dataset_description.json
│   └── pet1
│       ├── BIDS
│       │   ├── sub-OAS30010_ses-d0068_acq-AV45_pet.json
│       │   └── sub-OAS30010_ses-d0068_acq-AV45_pet.tsv
│       └── NIFTI
│           └── sub-OAS30010_ses-d0068_acq-AV45_pet.nii.gz
├── OAS30010_MR_d0068
│   ├── BIDS
│   │   └── dataset_description.json
│   ├── anat1
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_acq-TOF_angio.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_acq-TOF_angio.nii.gz
│   ├── anat2
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_acq-TSE_T2w.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_acq-TSE_T2w.nii.gz
│   ├── anat3
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_FLAIR.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_FLAIR.nii.gz
│   ├── anat4
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_T1w.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_T1w.nii.gz
│   ├── anat5
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_T2star.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_T2star.nii.gz
│   ├── dwi1
│   │   ├── BIDS
│   │   │   ├── sub-OAS30010_ses-d0068_run-01_dwi.bval
│   │   │   ├── sub-OAS30010_ses-d0068_run-01_dwi.bvec
│   │   │   └── sub-OAS30010_ses-d0068_run-01_dwi.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_run-01_dwi.nii.gz
│   ├── dwi2
│   │   ├── BIDS
│   │   │   ├── sub-OAS30010_ses-d0068_run-02_dwi.bval
│   │   │   ├── sub-OAS30010_ses-d0068_run-02_dwi.bvec
│   │   │   └── sub-OAS30010_ses-d0068_run-02_dwi.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_run-02_dwi.nii.gz
│   ├── fmap1
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_echo-1_run-01_fieldmap.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_echo-1_run-01_fieldmap.nii.gz
│   ├── fmap2
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_echo-2_run-01_fieldmap.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_echo-2_run-01_fieldmap.nii.gz
│   ├── fmap3
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_run-02_fieldmap.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_run-02_fieldmap.nii.gz
│   ├── func1
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_asl.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_asl.nii.gz
│   ├── func2
│   │   ├── BIDS
│   │   │   └── sub-OAS30010_ses-d0068_task-rest_run-01_bold.json
│   │   └── NIFTI
│   │       └── sub-OAS30010_ses-d0068_task-rest_run-01_bold.nii.gz
│   └── func3
│       ├── BIDS
│       │   └── sub-OAS30010_ses-d0068_task-rest_run-02_bold.json
│       └── NIFTI
│           └── sub-OAS30010_ses-d0068_task-rest_run-02_bold.nii.gz
```

I suspect we both used different means to download the data. We have used XNAT central for Clinica since it was the official channel available at the time.

Perhaps you have used these [download scripts](https://github.com/NrgXnat/oasis-scripts) instead? Their [example output](https://github.com/NrgXnat/oasis-scripts#download_scansdownload_oasis_scanssh) look quite close to yours.

**Comment by YasmineMH1997** [comment]
> > The viewer didn't show anything, unfortunately.
> 
> Then, I am not surprised the rest of your preprocessing is failing. The issue stands definitely within the source data and / or the converter.
> 
> > Also is the format of the installed OASIS 3 correct?
> 
> Mine differs slightly from yours.
> 
> ```
> ├── OAS30010_AV45_d0068
> │   ├── BIDS
> │   │   └── dataset_description.json
> │   └── pet1
> │       ├── BIDS
> │       │   ├── sub-OAS30010_ses-d0068_acq-AV45_pet.json
> │       │   └── sub-OAS30010_ses-d0068_acq-AV45_pet.tsv
> │       └── NIFTI
> │           └── sub-OAS30010_ses-d0068_acq-AV45_pet.nii.gz
> ├── OAS30010_MR_d0068
> │   ├── BIDS
> │   │   └── dataset_description.json
> │   ├── anat1
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_acq-TOF_angio.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_acq-TOF_angio.nii.gz
> │   ├── anat2
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_acq-TSE_T2w.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_acq-TSE_T2w.nii.gz
> │   ├── anat3
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_FLAIR.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_FLAIR.nii.gz
> │   ├── anat4
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_T1w.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_T1w.nii.gz
> │   ├── anat5
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_T2star.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_T2star.nii.gz
> │   ├── dwi1
> │   │   ├── BIDS
> │   │   │   ├── sub-OAS30010_ses-d0068_run-01_dwi.bval
> │   │   │   ├── sub-OAS30010_ses-d0068_run-01_dwi.bvec
> │   │   │   └── sub-OAS30010_ses-d0068_run-01_dwi.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_run-01_dwi.nii.gz
> │   ├── dwi2
> │   │   ├── BIDS
> │   │   │   ├── sub-OAS30010_ses-d0068_run-02_dwi.bval
> │   │   │   ├── sub-OAS30010_ses-d0068_run-02_dwi.bvec
> │   │   │   └── sub-OAS30010_ses-d0068_run-02_dwi.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_run-02_dwi.nii.gz
> │   ├── fmap1
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_echo-1_run-01_fieldmap.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_echo-1_run-01_fieldmap.nii.gz
> │   ├── fmap2
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_echo-2_run-01_fieldmap.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_echo-2_run-01_fieldmap.nii.gz
> │   ├── fmap3
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_run-02_fieldmap.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_run-02_fieldmap.nii.gz
> │   ├── func1
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_asl.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_asl.nii.gz
> │   ├── func2
> │   │   ├── BIDS
> │   │   │   └── sub-OAS30010_ses-d0068_task-rest_run-01_bold.json
> │   │   └── NIFTI
> │   │       └── sub-OAS30010_ses-d0068_task-rest_run-01_bold.nii.gz
> │   └── func3
> │       ├── BIDS
> │       │   └── sub-OAS30010_ses-d0068_task-rest_run-02_bold.json
> │       └── NIFTI
> │           └── sub-OAS30010_ses-d0068_task-rest_run-02_bold.nii.gz
> ```
> 
> I suspect we both used different means to download the data. We have used XNAT central for Clinica since it was the official channel available at the time.
> 
> Perhaps you have used these [download scripts](https://github.com/NrgXnat/oasis-scripts) instead? Their [example output](https://github.com/NrgXnat/oasis-scripts#download_scansdownload_oasis_scanssh) look quite close to yours.

The image of the source data is showing, but the preprocessed ones are not showing.

**Comment by YasmineMH1997** [comment]
I used the scripts in this link to download the data: 
https://github.com/NrgXnat/oasis-scripts

**Comment by YasmineMH1997** [comment]
I downloaded the data from XNAT 
And upgraded clinica to 0.7.5
But now it just does nothing whenever I use the command 
<img width="880" alt="image" src="https://github.com/aramis-lab/clinica/assets/128826190/c01a4fe4-8b48-43e7-b225-b7093614f564">
@ghisvail

**Comment by ghisvail** [comment]
>  I used the scripts in this link to download the data: https://github.com/NrgXnat/oasis-scripts

Now we know how your data were sourced. That's good progress towards triage 👍 

> The image of the source data is showing, but the ones in bids format after using clinica are corrupted.

So maybe an issue with how the converter works on Windows specifically.

> I downloaded the data from XNAT

Have you got a similar layout as mine or did it change?

Could you also give us the layout of your clinical files?

> And upgraded clinica to 0.7.5. But now it just does nothing whenever I use the command.

Thanks for checking out the latest version, and for your patience.

**Comment by YasmineMH1997** [comment]
@ghisvail 
I have one more question please. 
Should it take so long to convert? cz it used to be done right away. 
<img width="844" alt="image" src="https://github.com/aramis-lab/clinica/assets/128826190/c23b9e22-6717-4d98-b1b2-b43ea6c398fc">

**Comment by ghisvail** [comment]
It should be pretty quick considering all the converter does is processing clinical metadata and copying and renaming NIfTI files.

Speaking of clinical metadata, there are [specific instructions](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/OASIS3TOBIDS/) to follow in order for the converter to process sessions properly.

Did you check them out? If not, this could be the reason why the converter discards your source dataset.

**Comment by YasmineMH1997** [comment]
> Did you check them out? If not, this could be the reason why the converter discards your source dataset

Yes I did follow the instructions here: 
https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/OASIS3TOBIDS/

**Comment by YasmineMH1997** [comment]
@ghisvail 
I appreciate your patience and support. 
The terminal gets stuck on this clinica data have been found line. But there are files found in the bids folder. 
The bids validator shows two errors. May you advise me on them please: 
<img width="805" alt="image" src="https://github.com/aramis-lab/clinica/assets/128826190/5590938c-7226-480e-94ff-51c073a5a560">
<img width="834" alt="image" src="https://github.com/aramis-lab/clinica/assets/128826190/0c205cbb-d585-4167-a67c-89180f37a412">

**Comment by ghisvail** [comment]
The JSON metadata comes from OASIS3 directly, so any issues with non-compliance should probably be forwarded to them.

It's not a big deal for processing the images in NIfTI format.

> The terminal gets stuck on this clinica data have been found line. But there are files found in the bids folder.

So the converter is doing something at least.
