### ISSUE TITLE
ADNI2BIDS code optimization suggestions

### ISSUE THREAD

**Issue by CC0624** [aramis-lab/clinica#95]
In the function def select_scan_from_qc (scans_meta, mayo_mri_qc_subj, preferred_field_strength), I suggest adding a line (Bold part) as follows:
    if len (scans_meta.MagStrength.unique ())> 1:
         multiple_mag_strength = True
         # Save for later the scans with the non preferred magnetic field strength
         not_preferred_scan = scans_meta [scans_meta.MagStrength! = preferred_field_strength]
         # Filtering to keep only the scans with the preferred magnetic field strength
         scans_meta = scans_meta [scans_meta.MagStrength == preferred_field_strength]
     **_else:
         return select_scan_no_qc (scans_meta)_**
Because I found in the conversion process that in subject_id: 130_S_2373, there is only one sequence image loni_image: I302592, and it is marked as series_selected = 0 in the file "MAYOADIRL_MRI_IMAGEQC_12_08_15", so that an error will be reported during the program operation, and the following error will occur:
![image](https://user-images.githubusercontent.com/34269940/82139746-b89e0b80-985c-11ea-8beb-313312fe37be.png)

**Comment by alexandreroutier** [comment]
Hi,

Thank you for your suggestion regarding the converter.

We have currently few resources to investigate what will change in the BIDS folder if we add your suggestion. @jsampergonzalez, the main creator of the converter, has now a new job position and other contributors, me included, won't have time to look into details.

Best,
Alexandre

**Comment by 14thibea** [comment]
Hi,

I tried to reproduce the bug with subject 130_S_2373. I have the same characteristics in "MAYOADIRL_MRI_IMAGEQC_12_08_15".
I also tried by keeping only one line for this subject with loni image == I302592, and it also worked.
Do you still have this same problem?

**Comment by omar-rifai** [comment]
Closing issue as it seems outdated.
