### ISSUE TITLE
dti-preprocessing not generating .bvec files

### ISSUE THREAD

**Issue by ta4218** [aramis-lab/clinica#953]
**Description**
I have been running the dwi-preprocessing-using-t1 pipeline, the pipeline completes successfully, however, in the CAPS output folder, the .bvec files are missing. In the output directory, the expected files are:
-  <source_file>_space-T1w_preproc.{bval|bvec|nii.gz} 
- <source_file>_space-T1w_brainmask.nii.gz
However, no .bvec files are being generated. When I attempt to then run the dti-connectome pipeline, I receive the following error message.
![Screenshot from 2023-08-14 15-41-36](https://github.com/aramis-lab/clinica/assets/73485747/cbc5aae8-d36c-4205-819a-416bb3cfa909)

I am currently running clinica v.0.7.5 with Python=3.10. For this pipeline, I am using ANTs v2.3.1, and FSl 6.0.1. I have attached the pypeline.log below.

Any help is greatly appreciated.
Thank you

[pypeline.log](https://github.com/aramis-lab/clinica/files/12312817/pypeline.log)

**Comment by MatthieuJoulot** [comment]
Hi, I've looked into it a little, and it seems there was a regression in version `0.7.4`
If you're in a hurry, version `0.7.3` is working fine on my side, so i suggest you it !
If not, we'll correct it for the next release !
